### ISSUE TITLE
Errors on Windows:

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli-update#1045]
I'm using the Terminal in VS Code, which I think is git-bash?

I installed with `volta install ember-cli-update`

```
$ set DEBUG=ember-cli-update,boilerplate-update,git-diff-apply && ember-cli-update --to 3.16
internal/modules/cjs/loader.js:331
      throw err;
      ^

Error: Cannot find module 'C:\Users\Preston\Documents\Development\NullVoxPopuli\ember-query-params-service\node_modules\yam\node_modules\fs-extra\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:323:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:681:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:944:27)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Preston\Documents\Development\NullVoxPopuli\ember-query-params-service\node_modules\yam\lib\utils\io-utils.js:4:15)        
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\Preston\\Documents\\Development\\NullVoxPopuli\\ember-query-params-service\\node_modules\\yam\\node_modules\\fs-extra\\package.json',      
  requestPath: 'fs-extra'
}
internal/modules/cjs/loader.js:331
      throw err;
      ^

Error: Cannot find module 'C:\Users\Preston\Documents\Development\NullVoxPopuli\ember-query-params-service\node_modules\yam\node_modules\fs-extra\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:323:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:681:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:944:27)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Preston\Documents\Development\NullVoxPopuli\ember-query-params-service\node_modules\yam\lib\utils\io-utils.js:4:15)        
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\Preston\\Documents\\Development\\NullVoxPopuli\\ember-query-params-service\\node_modules\\yam\\node_modules\\fs-extra\\package.json',      
  requestPath: 'fs-extra'
}
Error: Command failed with exit code 1: node C:\Users\Preston\Documents\Development\NullVoxPopuli\ember-query-params-service\node_modules\ember-cli\bin\ember new my-project -sg -sn -sb -b addon --yarn --no-welcome
    at makeError (\\?\C:\Users\Preston\AppData\Local\Volta\tools\image\packages\ember-cli-update\0.54.6\node_modules\execa\lib\error.js:56:11)
    at handlePromise (\\?\C:\Users\Preston\AppData\Local\Volta\tools\image\packages\ember-cli-update\0.54.6\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async __runEmber (\\?\C:\Users\Preston\AppData\Local\Volta\tools\image\packages\ember-cli-update\0.54.6\src\get-start-and-end-commands.js:215:11)       
    at async _runEmber (\\?\C:\Users\Preston\AppData\Local\Volta\tools\image\packages\ember-cli-update\0.54.6\src\get-start-and-end-commands.js:231:11)        
    at async createProject (\\?\C:\Users\Preston\AppData\Local\Volta\tools\image\packages\ember-cli-update\0.54.6\src\get-start-and-end-commands.js:243:9)     
    at async _prepareCommand (\\?\C:\Users\Preston\AppData\Local\Volta\tools\image\packages\ember-cli-update\0.54.6\node_modules\boilerplate-update\src\get-start-and-end-commands.js:54:17)
    at async tryPrepareCommandUsingCache (\\?\C:\Users\Preston\AppData\Local\Volta\tools\image\packages\ember-cli-update\0.54.6\node_modules\boilerplate-update\src\get-start-and-end-commands.js:100:10)
    at async tryPrepareCommandUsingLocal (\\?\C:\Users\Preston\AppData\Local\Volta\tools\image\packages\ember-cli-update\0.54.6\node_modules\boilerplate-update\src\get-start-and-end-commands.js:123:19)
    at async AsyncFunction.prepareCommand (\\?\C:\Users\Preston\AppData\Local\Volta\tools\image\packages\ember-cli-update\0.54.6\node_modules\boilerplate-update\src\get-start-and-end-commands.js:183:17)
    at async Promise.all (index 0)
    at async getStartAndEndCommands (\\?\C:\Users\Preston\AppData\Local\Volta\tools\image\packages\ember-cli-update\0.54.6\node_modules\boilerplate-update\src\get-start-and-end-commands.js:37:7)
    at async boilerplateUpdate (\\?\C:\Users\Preston\AppData\Local\Volta\tools\image\packages\ember-cli-update\0.54.6\node_modules\boilerplate-update\src\index.js:122:20)
    at async emberCliUpdate (\\?\C:\Users\Preston\AppData\Local\Volta\tools\image\packages\ember-cli-update\0.54.6\src\index.js:175:7)
    at async Object.handler (\\?\C:\Users\Preston\AppData\Local\Volta\tools\image\packages\ember-cli-update\0.54.6\bin\commands\default.js:32:16) {
  command: 'node C:\\Users\\Preston\\Documents\\Development\\NullVoxPopuli\\ember-query-params-service\\node_modules\\ember-cli\\bin\\ember new my-project -sg 
-sn -sb -b addon --yarn --no-welcome',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
installing addon
Ember CLI v3.16.1

Creating a new Ember addon in C:\Users\Preston\AppData\Local\Temp\tmp-16504La238rJhnklt\ember-query-params-service:
  create .editorconfig
  create .ember-cli
  create .eslintignore
  create .eslintrc.js
  create .template-lintrc.js
  create .travis.yml
  create .watchmanconfig
  create README.md
  create tests\dummy\app\app.js
  create tests\dummy\app\components\.gitkeep
  create tests\dummy\app\controllers\.gitkeep
  create tests\dummy\app\helpers\.gitkeep
  create tests\dummy\app\index.html
  create tests\dummy\app\models\.gitkeep
  create tests\dummy\app\router.js
  create tests\dummy\app\routes\.gitkeep
  create tests\dummy\app\styles\app.css
  create tests\dummy\app\templates\application.hbs
  create tests\dummy\config\environment.js
  create tests\dummy\config\optional-features.json
  create tests\dummy\config\targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create tests\dummy\public\robots.txt
  create testem.js
  create tests\helpers\.gitkeep
  create tests\index.html
  create tests\integration\.gitkeep
  create tests\test-helper.js
  create tests\unit\.gitkeep
  create vendor\.gitkeep
  create CONTRIBUTING.md
  create LICENSE.md
  create config\ember-try.js
  create config\environment.js
  create addon\.gitkeep
  create app\.gitkeep
  create index.js
  create .npmignore

Successfully created project ember-query-params-service.
Get started by typing:

  $ cd ember-query-params-service
  $ yarn start

Happy coding!

Preston@DESKTOP-M3I5GE2 MINGW64 ~/Documents/Development/NullVoxPopuli/ember-query-params-service (modernize)
$

Preston@DESKTOP-M3I5GE2 MINGW64 ~/Documents/Development/NullVoxPopuli/ember-query-params-service (modernize)
$ git status
On branch modernize
Your branch is up to date with 'origin/modernize'.

nothing to commit, working tree clean

Preston@DESKTOP-M3I5GE2 MINGW64 ~/Documents/Development/NullVoxPopuli/ember-query-params-service (modernize)
$ cat package.json | grep ember-source
    "ember-source": "3.11.0-beta.2",

Preston@DESKTOP-M3I5GE2 MINGW64 ~/Documents/Development/NullVoxPopuli/ember-query-params-service (modernize)

```

**Comment by kellyselden** [comment]
I think you have some symlink issues. Try nuking node_modules first.
