### ISSUE TITLE
`Error: Cannot find module` on Windows

### ISSUE THREAD

**Issue by charlesfries** [ember-cli/ember-cli-update#1147]
When I run `ember-cli-update` globally on my Windows machine, I get a `Cannot find module` error. I think this might be because I have a space in my username and user folder.

```
$ set DEBUG=ember-cli-update,boilerplate-update,git-diff-apply; ember-cli-update
? Blueprint updates have been found. Which one would you like to update? app, current: 3.25.2, latest: 3.26.1
? Do you want the latest version? 3.26.1 (latest)
installing app
Ember CLI v3.26.1

Creating a new Ember app in C:\Users\CHARLE~1\AppData\Local\Temp\tmp-12228-8OxWRQmGWuEd\myapp:
  create .editorconfig
  create .ember-cli
  create .eslintignore
  create .eslintrc.js
  create .prettierignore
  create .prettierrc.js
  create .template-lintrc.js
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app\app.js
  create app\components\.gitkeep
  create app\controllers\.gitkeep
  create app\helpers\.gitkeep
  create app\index.html
  create app\models\.gitkeep
  create app\router.js
  create app\routes\.gitkeep
  create app\styles\app.css
  create app\templates\application.hbs
  create config\ember-cli-update.json
  create config\environment.js
  create config\optional-features.json
  create config\targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public\robots.txt
  create testem.js
  create tests\helpers\.gitkeep
  create tests\index.html
  create tests\integration\.gitkeep
  create tests\test-helper.js
  create tests\unit\.gitkeep
  create vendor\.gitkeep

Successfully created project myapp.
Get started by typing:

  $ cd myapp
  $ npm start

Happy coding!
installing app
Ember CLI v3.26.1

Creating a new Ember app in C:\Users\CHARLE~1\AppData\Local\Temp\tmp-12228-xZLF7hrLyueo\myapp:
  create .editorconfig
  create .ember-cli
  create .eslintignore
  create .eslintrc.js
  create .prettierignore
  create .prettierrc.js
  create .template-lintrc.js
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app\app.js
  create app\components\.gitkeep
  create app\controllers\.gitkeep
  create app\helpers\.gitkeep
  create app\index.html
  create app\models\.gitkeep
  create app\router.js
  create app\routes\.gitkeep
  create app\styles\app.css
  create app\templates\application.hbs
  create config\ember-cli-update.json
  create config\environment.js
  create config\optional-features.json
  create config\targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public\robots.txt
  create testem.js
  create tests\helpers\.gitkeep
  create tests\index.html
  create tests\integration\.gitkeep
  create tests\test-helper.js
  create tests\unit\.gitkeep
  create vendor\.gitkeep

Successfully created project myapp.
Get started by typing:

  $ cd myapp
  $ npm start

Happy coding!
Error: Command failed: node C:\Users\Charles Fries\AppData\Roaming\npm\node_modules\ember-cli-update\node_modules\cpr\bin\cpr C:\Users\CHARLE~1\AppData\Local\Temp\tmp-12228-xZLF7hrLyueo\myapp.
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\Charles'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node C:\\Users\\Charles Fries\\AppData\\Roaming\\npm\\node_modules\\ember-cli-update\\node_modules\\cpr\\bin\\cpr C:\\Users\\CHARLE~1\\AppData\\Local\\Temp\\tmp-12228-xZLF7hrLyueo\\myapp.',
  stdout: '',
  stderr: 'internal/modules/cjs/loader.js:905\r\n' +
    '  throw err;\r\n' +
    '  ^\r\n' +
    '\r\n' +
    "Error: Cannot find module 'C:\\Users\\Charles'\r\n" +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)\r\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:746:27)\r\n' +
    '    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)\r\n' +
    '    at internal/main/run_main_module.js:17:47 {\r\n' +
    "  code: 'MODULE_NOT_FOUND',\r\n" +
    '  requireStack: []\r\n' +
    '}\r\n'
}
```

**Comment by charlesfries** [comment]
Duplicate of #687
