### ISSUE TITLE
Error: not supported

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli-update#1160]
After successful ember-cli-update to 3.28.3

```
ember -v
ember-cli: 3.28.3
node: 12.16.1
os: darwin x64
```

`--run-codemods` fails with `Error: Not supported`

```
DEBUG=ember-cli-update,boilerplate-update,git-diff-apply ember-cli-update --run-codemods
? Which blueprint would you like to run codemods for? ember-cli
Error: Not supported
    at getApplicableCodemods (/Users/bryan/.config/yarn/global/node_modules/boilerplate-update/src/get-applicable-codemods.js:19:32)
    at async getAndPromptCodemods (/Users/bryan/.config/yarn/global/node_modules/boilerplate-update/src/get-and-prompt-codemods.js:12:18)
    at async promptAndRunCodemods (/Users/bryan/.config/yarn/global/node_modules/boilerplate-update/src/prompt-and-run-codemods.js:13:18)
    at async codemods (/Users/bryan/.config/yarn/global/node_modules/ember-cli-update/src/codemods.js:80:10)
    at async Object.handler (/Users/bryan/.config/yarn/global/node_modules/ember-cli-update/bin/commands/default.js:42:19)
```

**Comment by BryanCrotaz** [comment]
Only happens in node 12. Node 14 works, but isn't supported by ember-cli, so it's pain to switch back and forth.

**Comment by NotGrm** [comment]
Hey, @BryanCrotaz do you found a fix for your issue? I encountered the same issue after trying to update my app from 3.14 to 3.28 and I did not manage to execute the `--run-codemods` command. Every time I get the same backtrace.

Switching Node version does not seems to fix anything for me

**Comment by BryanCrotaz** [comment]
I've found that the codemods themselves only work up to node 10, (otherwise the dreaded cb.apply is undefined), but ember-cli-update only works in node 12 and above.

**Comment by BryanCrotaz** [comment]
#1167

**Comment by Yelinz** [comment]
Nearly all codemods work for upgrading from 3.20 to 4.0 me with node 14.4, see https://github.com/ember-cli/ember-cli-update/issues/1105#issuecomment-1293170195 for problems with `cb.apply`
