### ISSUE TITLE
Deprecation 'template-compiler.registerPlugin' does not provide enough information

### ISSUE THREAD

**Issue by LeopoldHock** [ember-cli/ember-cli-update#1164]
The following deprecation warning does not give me any information about what plugin is causing it.

Deprecation ID: `template-compiler.registerPlugin`
This is the console output:
https://deprecations.emberjs.com/v3.x/#toc_template-compiler-registerPlugin
```
| building... [Babel: ember-popper > applyPatches]
DEPRECATION: Using class based template compilation plugins is deprecated, please update to the functional style: SetTransform [deprecation id: template-compiler.registerPlugin]
        at logDeprecationStackTrace (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:1984:21)
        at HANDLERS.<computed> (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:2117:9)
        at raiseOnDeprecation (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:2011:9)
        at HANDLERS.<computed> (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:2117:9)
        at invoke (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:2129:9)
        at deprecate (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:2085:28)
        at wrapLegacyPluginIfNeeded (C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:20501:49)
        at C:\<my-project>\node_modules\ember-source\dist\ember-template-compiler.js:20482:16
        at Array.map (<anonymous>)
```

Maybe adding information required to find the plugin would be beneficial?

ember-cli: 3.28.4
ember-source: 3.28.8

**Comment by LeopoldHock** [comment]
Ooops, wrong repository. Closing the issue.

**Comment by cah-briangantzler** [comment]
I am still having this issue, what repo did you eventually post in, could you reference here for a link please

**Comment by LeopoldHock** [comment]
Hey @cah-briangantzler! I posted the issue here: https://github.com/ember-cli/ember-cli/issues/9738
