### ISSUE TITLE
Error while running:  ember-cli-update

### ISSUE THREAD

**Issue by Anil-Bhimwal1** [ember-cli/ember-cli-update#1218]
<img width="1440" alt="Screenshot 2022-11-11 at 6 26 41 PM" src="https://user-images.githubusercontent.com/70019507/201345573-80746099-9255-4110-8a18-92f6708365d1.png">
I am trying to upgrade ember from 2.4.1 to latest version as this version have dependency on jquery 2.2.4 version which is vulnerable to multiple attacks. 
while running i am getting this error :  

ember[32429]: ../src/node_contextify.cc:686:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x101323515 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000b6609 node::Abort() [/usr/local/bin/node]
 3: 0x1000b6471 node::Assert(node::AssertionInfo const&) [/usr/local/bin/node]
 4: 0x1000a9c84 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 5: 0x1002724a8 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 6: 0x10027175c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 7: 0x10027117f v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 8: 0x100a8ed19 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
ember[32432]: ../src/node_contextify.cc:686:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x101323515 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000b6609 node::Abort() [/usr/local/bin/node]
 3: 0x1000b6471 node::Assert(node::AssertionInfo const&) [/usr/local/bin/node]
 4: 0x1000a9c84 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 5: 0x1002724a8 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 6: 0x10027175c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 7: 0x10027117f v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 8: 0x100a8ed19 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
Error: Command was killed with SIGABRT (Aborted): node /Users/Desktop/Projects/sample/client/node_modules/ember-cli/bin/ember new my-project -sg -sn -sb -b app --no-welcome
    at makeError (/usr/local/lib/node_modules/ember-cli-update/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/local/lib/node_modules/ember-cli-update/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async __runEmber (/usr/local/lib/node_modules/ember-cli-update/src/get-start-and-end-commands.js:214:11)
    at async _runEmber (/usr/local/lib/node_modules/ember-cli-update/src/get-start-and-end-commands.js:230:11)
    at async createProject (/usr/local/lib/node_modules/ember-cli-update/src/get-start-and-end-commands.js:245:9)
    at async _prepareCommand (/usr/local/lib/node_modules/ember-cli-update/node_modules/boilerplate-update/src/get-start-and-end-commands.js:54:17)
    at async tryPrepareCommandUsingCache (/usr/local/lib/node_modules/ember-cli-update/node_modules/boilerplate-update/src/get-start-and-end-commands.js:100:10)
    at async tryPrepareCommandUsingLocal (/usr/local/lib/node_modules/ember-cli-update/node_modules/boilerplate-update/src/get-start-and-end-commands.js:123:19)
    at async AsyncFunction.prepareCommand (/usr/local/lib/node_modules/ember-cli-update/node_modules/boilerplate-update/src/get-start-and-end-commands.js:183:17) {
  shortMessage: 'Command was killed with SIGABRT (Aborted): node /Users/anil.bhimwal/Desktop/Projects/website-corporate/client/node_modules/ember-cli/bin/ember new my-project -sg -sn -sb -b app --no-welcome',
  command: 'node /Users/anil.bhimwal/Desktop/Projects/website-corporate/client/node_modules/ember-cli/bin/ember new my-project -sg -sn -sb -b app --no-welcome',
  escapedCommand: 'node "/Users/anil.bhimwal/Desktop/Projects/website-corporate/client/node_modules/ember-cli/bin/ember" new my-project -sg -sn -sb -b app --no-welcome',
  exitCode: undefined,
  signal: 'SIGABRT',
  signalDescription: 'Aborted',
  stdout: '',
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

please help me to resolve this

**Comment by Anil-Bhimwal1** [comment]
anyone please help
