### ISSUE TITLE
Error running ember update on Windows

### ISSUE THREAD

**Issue by yohanmishkin** [ember-cli/ember-cli-update#329]
Sorry for the vague issue title! 

My hunch is that the issue may be related to usage of `execSync` as I've had issues in the past with Windows and Ember addons ([reference](https://github.com/embermap/ember-cli-tailwind/pull/3)).

Console output:
```
λ set DEBUG=ember-cli-update,git-diff-apply && ember update
  ember-cli-update npm info ember-cli versions --json +0ms
  ember-cli-update [
  ember-cli-update   "0.0.0",
  ember-cli-update   "0.0.1",
  ember-cli-update   "0.0.2",
  ember-cli-update   "0.0.3",
  ember-cli-update   "0.0.4",
  ember-cli-update   "0.0.5",
  ember-cli-update   "0.0.6",
  ember-cli-update   "0.0.7",
  ember-cli-update   "0.0.8",
  ember-cli-update   "0.0.9",
  ember-cli-update   "0.0.10",
  ember-cli-update   "0.0.11",
  ember-cli-update   "0.0.12",
  ember-cli-update   "0.0.13",
  ember-cli-update   "0.0.14",
  ember-cli-update   "0.0.15",
  ember-cli-update   "0.0.16",
  ember-cli-update   "0.0.18",
  ember-cli-update   "0.0.19",
  ember-cli-update   "0.0.20",
  ember-cli-update   "0.0.21",
  ember-cli-update   "0.0.22",
  ember-cli-update   "0.0.23",
  ember-cli-update   "0.0.24",
  ember-cli-update   "0.0.25",
  ember-cli-update   "0.0.27",
  ember-cli-update   "0.0.28",
  ember-cli-update   "0.0.29",
  ember-cli-update   "0.0.32",
  ember-cli-update   "0.0.33",
  ember-cli-update   "0.0.34",
  ember-cli-update   "0.0.35",
  ember-cli-update   "0.0.36",
  ember-cli-update   "0.0.37",
  ember-cli-update   "0.0.38",
  ember-cli-update   "0.0.39",
  ember-cli-update   "0.0.40",
  ember-cli-update   "0.0.41",
  ember-cli-update   "0.0.42",
  ember-cli-update   "0.0.43",
  ember-cli-update   "0.0.44",
  ember-cli-update   "0.0.45",
  ember-cli-update   "0.0.46",
  ember-cli-update   "0.0.47",
  ember-cli-update   "0.1.0",
  ember-cli-update   "0.1.1",
  ember-cli-update   "0.1.2",
  ember-cli-update   "0.1.3",
  ember-cli-update   "0.1.4",
  ember-cli-update   "0.1.5",
  ember-cli-update   "0.1.6",
  ember-cli-update   "0.1.7",
  ember-cli-update   "0.1.8",
  ember-cli-update   "0.1.9",
  ember-cli-update   "0.1.10",
  ember-cli-update   "0.1.11",
  ember-cli-update   "0.1.12",
  ember-cli-update   "0.1.13",
  ember-cli-update   "0.1.14",
  ember-cli-update   "0.1.15",
  ember-cli-update   "0.2.0-beta.1",
  ember-cli-update   "0.2.0",
  ember-cli-update   "0.2.1",
  ember-cli-update   "0.2.2",
  ember-cli-update   "0.2.3",
  ember-cli-update   "0.2.4",
  ember-cli-update   "0.2.5",
  ember-cli-update   "0.2.6",
  ember-cli-update   "0.2.7",
  ember-cli-update   "1.13.0",
  ember-cli-update   "1.13.1",
  ember-cli-update   "1.13.5",
  ember-cli-update   "1.13.6",
  ember-cli-update   "1.13.7",
  ember-cli-update   "1.13.8",
  ember-cli-update   "1.13.9",
  ember-cli-update   "1.13.10",
  ember-cli-update   "1.13.11",
  ember-cli-update   "1.13.12",
  ember-cli-update   "1.13.13",
  ember-cli-update   "1.13.14",
  ember-cli-update   "1.13.15",
  ember-cli-update   "2.2.0-beta.1",
  ember-cli-update   "2.2.0-beta.2",
  ember-cli-update   "2.2.0-beta.3",
  ember-cli-update   "2.2.0-beta.4",
  ember-cli-update   "2.2.0-beta.5",
  ember-cli-update   "2.2.0-beta.6",
  ember-cli-update   "2.3.0-beta.1",
  ember-cli-update   "2.3.0-beta.2",
  ember-cli-update   "2.3.0",
  ember-cli-update   "2.4.0",
  ember-cli-update   "2.4.1",
  ember-cli-update   "2.4.2",
  ember-cli-update   "2.4.3",
  ember-cli-update   "2.5.0",
  ember-cli-update   "2.5.1",
  ember-cli-update   "2.6.0-beta.1",
  ember-cli-update   "2.6.0-beta.2",
  ember-cli-update   "2.6.0-beta.3",
  ember-cli-update   "2.6.0",
  ember-cli-update   "2.6.1",
  ember-cli-update   "2.6.2",
  ember-cli-update   "2.6.3",
  ember-cli-update   "2.7.0-beta.1",
  ember-cli-update   "2.7.0-beta.2",
  ember-cli-update   "2.7.0-beta.3",
  ember-cli-update   "2.7.0-beta.4",
  ember-cli-update   "2.7.0-beta.5",
  ember-cli-update   "2.7.0-beta.6",
  ember-cli-update   "2.7.0",
  ember-cli-update   "2.8.0-beta.1",
  ember-cli-update   "2.8.0-beta.2",
  ember-cli-update   "2.8.0-beta.3",
  ember-cli-update   "2.8.0",
  ember-cli-update   "2.9.0-beta.1",
  ember-cli-update   "2.9.0-beta.2",
  ember-cli-update   "2.9.0",
  ember-cli-update   "2.9.1",
  ember-cli-update   "2.10.0-beta.1",
  ember-cli-update   "2.10.0-beta.2",
  ember-cli-update   "2.10.0",
  ember-cli-update   "2.10.1",
  ember-cli-update   "2.11.0-beta.1",
  ember-cli-update   "2.11.0-beta.2",
  ember-cli-update   "2.11.0",
  ember-cli-update   "2.11.1",
  ember-cli-update   "2.12.0-beta.1",
  ember-cli-update   "2.12.0-beta.2",
  ember-cli-update   "2.12.0",
  ember-cli-update   "2.12.1",
  ember-cli-update   "2.12.2",
  ember-cli-update   "2.12.3",
  ember-cli-update   "2.13.0-beta.1",
  ember-cli-update   "2.13.0-beta.2",
  ember-cli-update   "2.13.0-beta.3",
  ember-cli-update   "2.13.0-beta.4",
  ember-cli-update   "2.13.0",
  ember-cli-update   "2.13.1",
  ember-cli-update   "2.13.2",
  ember-cli-update   "2.13.3",
  ember-cli-update   "2.14.0-beta.1",
  ember-cli-update   "2.14.0-beta.2",
  ember-cli-update   "2.14.0",
  ember-cli-update   "2.14.1",
  ember-cli-update   "2.14.2",
  ember-cli-update   "2.15.0-beta.1",
  ember-cli-update   "2.15.0-beta.2",
  ember-cli-update   "2.15.0",
  ember-cli-update   "2.15.1",
  ember-cli-update   "2.16.0-beta.1",
  ember-cli-update   "2.16.0-beta.2",
  ember-cli-update   "2.16.0",
  ember-cli-update   "2.16.1",
  ember-cli-update   "2.16.2",
  ember-cli-update   "2.17.0-beta.1",
  ember-cli-update   "2.17.0-beta.2",
  ember-cli-update   "2.17.0",
  ember-cli-update   "2.17.1",
  ember-cli-update   "2.17.2",
  ember-cli-update   "2.18.0-beta.1",
  ember-cli-update   "2.18.0-beta.2",
  ember-cli-update   "2.18.0",
  ember-cli-update   "2.18.1",
  ember-cli-update   "2.18.2",
  ember-cli-update   "3.0.0-beta.1",
  ember-cli-update   "3.0.0-beta.2",
  ember-cli-update   "3.0.0",
  ember-cli-update   "3.0.1",
  ember-cli-update   "3.0.2",
  ember-cli-update   "3.0.3",
  ember-cli-update   "3.0.4",
  ember-cli-update   "3.1.0-beta.1",
  ember-cli-update   "3.1.0",
  ember-cli-update   "3.1.1",
  ember-cli-update   "3.1.2",
  ember-cli-update   "3.2.0-beta.1"
  ember-cli-update ]
  ember-cli-update  +3s
  ember-cli-update npm info ember-cli@latest version --json +247ms
  ember-cli-update "3.1.2"
  ember-cli-update  +3s
  git-diff-apply git status --porcelain +0ms
  git-diff-apply  +176ms
  git-diff-apply git clone --mirror https://github.com/ember-cli/ember-new-output C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876pftCWhUKKkk1\.git +4ms
Cloning into bare repository 'C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876pftCWhUKKkk1\.git'...
  git-diff-apply  +2s
  git-diff-apply git --git-dir="C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876pftCWhUKKkk1\.git" rev-parse v3.0.2 +2ms
  git-diff-apply ab945abab374ca27ba3502fa438f0a123bcb9a30
  git-diff-apply  +147ms
  git-diff-apply git --git-dir="C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876pftCWhUKKkk1\.git" --work-tree="C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876pftCWhUKKkk1" checkout ab945abab374ca27ba3502fa438f0a123bcb9a30 +4ms
Note: checking out 'ab945abab374ca27ba3502fa438f0a123bcb9a30'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ab945ab 3.0.2
  git-diff-apply  +486ms
  git-diff-apply git --git-dir="C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876pftCWhUKKkk1\.git" rev-parse v3.1.2 +16ms
  git-diff-apply 122ae4b547a8487a426a52f58244db6822bd4092
  git-diff-apply  +237ms
  git-diff-apply git --git-dir="C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876pftCWhUKKkk1\.git" --work-tree="C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876pftCWhUKKkk1" checkout 122ae4b547a8487a426a52f58244db6822bd4092 +2ms
Previous HEAD position was ab945ab 3.0.2
HEAD is now at 122ae4b 3.1.2
  git-diff-apply  +270ms
  git-diff-apply git rev-parse --show-toplevel +0ms
  git-diff-apply C:/dev/blahblahblah/marketplace-front
  git-diff-apply  +119ms
  git-diff-apply git --git-dir="C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876pftCWhUKKkk1\.git" rev-parse v3.0.2 +7ms
  git-diff-apply ab945abab374ca27ba3502fa438f0a123bcb9a30
  git-diff-apply  +138ms
  git-diff-apply git --git-dir="C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876pftCWhUKKkk1\.git" --work-tree="C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876pftCWhUKKkk1" checkout ab945abab374ca27ba3502fa438f0a123bcb9a30 +4ms
Previous HEAD position was 122ae4b 3.1.2
HEAD is now at ab945ab 3.0.2
  git-diff-apply  +163ms
  git-diff-apply chdir C:/dev/blahblahblah/marketplace-front +0ms
  git-diff-apply git symbolic-ref --short HEAD +0ms
  git-diff-apply master
  git-diff-apply  +154ms
  git-diff-apply git checkout --orphan 5507d000-4a4e-11e8-98fa-6d4ec813e719 +4ms
Switched to a new branch '5507d000-4a4e-11e8-98fa-6d4ec813e719'
  git-diff-apply  +183ms
  git-diff-apply git reset --hard +8ms
  git-diff-apply  +180ms
  git-diff-apply ensureDirSync C:\dev\blahblahblah\marketplace-front +533ms
  git-diff-apply chdir C:\dev\blahblahblah\marketplace-front +0ms
  git-diff-apply [ '.editorconfig',
  git-diff-apply   '.ember-cli',
  git-diff-apply   '.eslintrc.js',
  git-diff-apply   '.git',
  git-diff-apply   '.gitignore',
  git-diff-apply   '.travis.yml',
  git-diff-apply   '.watchmanconfig',
  git-diff-apply   'app',
  git-diff-apply   'config',
  git-diff-apply   'ember-cli-build.js',
  git-diff-apply   'package.json',
  git-diff-apply   'public',
  git-diff-apply   'README.md',
  git-diff-apply   'testem.js',
  git-diff-apply   'tests',
  git-diff-apply   'vendor' ] +0ms
  git-diff-apply copy C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876pftCWhUKKkk1 C:\dev\blahblahblah\marketplace-front +32ms
  git-diff-apply git add -A +126ms
  git-diff-apply  +292ms
  git-diff-apply git status --porcelain +4ms
  git-diff-apply A  .editorconfig
  git-diff-apply A  .ember-cli
  git-diff-apply A  .eslintrc.js
  git-diff-apply A  .gitignore
  git-diff-apply A  .travis.yml
  git-diff-apply A  .watchmanconfig
  git-diff-apply A  README.md
  git-diff-apply A  app/app.js
  git-diff-apply A  app/components/.gitkeep
  git-diff-apply A  app/controllers/.gitkeep
  git-diff-apply A  app/helpers/.gitkeep
  git-diff-apply A  app/index.html
  git-diff-apply A  app/models/.gitkeep
  git-diff-apply A  app/resolver.js
  git-diff-apply A  app/router.js
  git-diff-apply A  app/routes/.gitkeep
  git-diff-apply A  app/styles/app.css
  git-diff-apply A  app/templates/application.hbs
  git-diff-apply A  app/templates/components/.gitkeep
  git-diff-apply A  config/environment.js
  git-diff-apply A  config/targets.js
  git-diff-apply A  ember-cli-build.js
  git-diff-apply A  package.json
  git-diff-apply A  public/robots.txt
  git-diff-apply A  testem.js
  git-diff-apply A  tests/helpers/.gitkeep
  git-diff-apply A  tests/index.html
  git-diff-apply A  tests/integration/.gitkeep
  git-diff-apply A  tests/test-helper.js
  git-diff-apply A  tests/unit/.gitkeep
  git-diff-apply A  vendor/.gitkeep
  git-diff-apply  +150ms
  git-diff-apply git commit -m "message" +57ms
  git-diff-apply [5507d000-4a4e-11e8-98fa-6d4ec813e719 (root-commit) b4f981b] message
  git-diff-apply  31 files changed, 442 insertions(+)
  git-diff-apply  create mode 100644 .editorconfig
  git-diff-apply  create mode 100644 .ember-cli
  git-diff-apply  create mode 100644 .eslintrc.js
  git-diff-apply  create mode 100644 .gitignore
  git-diff-apply  create mode 100644 .travis.yml
  git-diff-apply  create mode 100644 .watchmanconfig
  git-diff-apply  create mode 100644 README.md
  git-diff-apply  create mode 100644 app/app.js
  git-diff-apply  create mode 100644 app/components/.gitkeep
  git-diff-apply  create mode 100644 app/controllers/.gitkeep
  git-diff-apply  create mode 100644 app/helpers/.gitkeep
  git-diff-apply  create mode 100644 app/index.html
  git-diff-apply  create mode 100644 app/models/.gitkeep
  git-diff-apply  create mode 100644 app/resolver.js
  git-diff-apply  create mode 100644 app/router.js
  git-diff-apply  create mode 100644 app/routes/.gitkeep
  git-diff-apply  create mode 100644 app/styles/app.css
  git-diff-apply  create mode 100644 app/templates/application.hbs
  git-diff-apply  create mode 100644 app/templates/components/.gitkeep
  git-diff-apply  create mode 100644 config/environment.js
  git-diff-apply  create mode 100644 config/targets.js
  git-diff-apply  create mode 100644 ember-cli-build.js
  git-diff-apply  create mode 100644 package.json
  git-diff-apply  create mode 100644 public/robots.txt
  git-diff-apply  create mode 100644 testem.js
  git-diff-apply  create mode 100644 tests/helpers/.gitkeep
  git-diff-apply  create mode 100644 tests/index.html
  git-diff-apply  create mode 100644 tests/integration/.gitkeep
  git-diff-apply  create mode 100644 tests/test-helper.js
  git-diff-apply  create mode 100644 tests/unit/.gitkeep
  git-diff-apply  create mode 100644 vendor/.gitkeep
  git-diff-apply  +390ms
  git-diff-apply git --git-dir="C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876pftCWhUKKkk1\.git" diff v3.0.2 v3.1.2 > C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876VqVaNS6q4UJl\file.patch +54ms
  git-diff-apply  +184ms
  git-diff-apply git apply C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876VqVaNS6q4UJl\file.patch +3ms
error: patch failed: .eslintrc.js:20
error: .eslintrc.js: patch does not apply
error: patch failed: package.json:19
error: package.json: patch does not apply
  git-diff-apply git clean -f +138ms
  git-diff-apply  +140ms
  git-diff-apply git reset --hard +0ms
  git-diff-apply HEAD is now at b4f981b message
  git-diff-apply  +152ms
  git-diff-apply git checkout master +4ms
Switched to branch 'master'
  git-diff-apply  +957ms
  git-diff-apply git branch -D 5507d000-4a4e-11e8-98fa-6d4ec813e719 +0ms
  git-diff-apply Deleted branch 5507d000-4a4e-11e8-98fa-6d4ec813e719 (was b4f981b).
  git-diff-apply  +123ms
File: C:\WINDOWS\system32\cmd.exe

Command failed: git apply C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876VqVaNS6q4UJl\file.patch
error: patch failed: .eslintrc.js:20
error: .eslintrc.js: patch does not apply
error: patch failed: package.json:19
error: package.json: patch does not apply



Stack Trace and Error Report: C:\Users\YOHANM~1\AppData\Local\Temp/error.dump.a5e8783c59daf80906f9de3db6f0959a.log
```

Error log:
```
=================================================================================

ENV Summary:

  TIME: Fri Apr 27 2018 15:08:27 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Users\yohanmishkin\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
  - update
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\YOHANM~1\AppData\Local\Temp
  SHELL: null
  PATH:
  - C
  - \Program Files (x86)\Cmder\bin;C
  - \Program Files (x86)\Cmder\vendor\conemu-maximus5\ConEmu\Scripts;C
  - \Program Files (x86)\Cmder\vendor\conemu-maximus5;C
  - \Program Files (x86)\Cmder\vendor\conemu-maximus5\ConEmu;C
  - \ProgramData\Oracle\Java\javapath;C
  - \Program Files\Docker\Docker\Resources\bin;C
  - \Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C
  - \Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \Program Files (x86)\HashiCorp\Vagrant\bin;C
  - \Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C
  - \Program Files (x86)\Heroku\bin;C
  - \Program Files (x86)\git\cmd;C
  - \Program Files\Microsoft SQL Server\130\Tools\Binn\;C
  - \Program Files\dotnet\;C
  - \Program Files\Amazon\AWSCLI\;C
  - \Program Files\Python36;C
  - \Program Files\PuTTY\;C
  - \Program Files\Heroku\bin;C
  - \Program Files\Sublime Text 3;C
  - \Program Files (x86)\Yarn\bin;C
  - \Program Files\Jetbrains\JetBrains Rider 2017.2.1\bin\;C
  - \Users\yohanmishkin\AppData\Local\Programs\Git\cmd;C
  - \Program Files\nodejs\;C
  - \Ruby24-x64\bin;C
  - \Ruby23-x64\bin;C
  - \Users\yohanmishkin\AppData\Local\Programs\Git\cmd1;C
  - \Users\yohanmishkin\AppData\Local\Microsoft\WindowsApps;C
  - \dev\lib\ffmpeg\bin;C
  - \Users\yohanmishkin\AppData\Local\Programs\Python\Python36;C
  - \Users\yohanmishkin\AppData\Local\Programs\Python\Python36\Scripts;C
  - \dev\lib;C
  - \Program Files\Microsoft VS Code\bin;C
  - \Program Files\JetBrains\PyCharm Community Edition 2017.2.3\bin\;C
  - \Users\yohanmishkin\AppData\Local\Yarn\bin;C
  - \Users\yohanmishkin\AppData\Roaming\npm;C
  - \Users\yohanmishkin\AppData\Local\hyper\app-2.1.0-canary1\resources\bin;C
  - \Users\yohanmishkin\AppData\Local\Programs\Git\usr\bin;C
  - \Users\yohanmishkin\AppData\Local\Programs\Git\usr\share\vim\vim74;C
  - \Program Files (x86)\Cmder\
  PLATFORM: win32 x64
  FREEMEM: 2767069184
  TOTALMEM: 8511606784
  UPTIME: 88522.6634622
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz - 2808
  - Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz - 2808
  - Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz - 2808
  - Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz - 2808
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 31.0.1
  - http_parser: 2.7.0
  - icu: 59.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.9.4
  - openssl: 1.0.2n
  - tz: 2017b
  - unicode: 9.0
  - uv: 1.15.0
  - v8: 6.1.534.50
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Command failed: git apply C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876VqVaNS6q4UJl\file.patch
error: patch failed: .eslintrc.js:20
error: .eslintrc.js: patch does not apply
error: patch failed: package.json:19
error: package.json: patch does not apply

  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: C:\WINDOWS\system32\cmd.exe
    - line: [undefined]
  - message: Command failed: git apply C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876VqVaNS6q4UJl\file.patch
error: patch failed: .eslintrc.js:20
error: .eslintrc.js: patch does not apply
error: patch failed: package.json:19
error: package.json: patch does not apply

  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Command failed: git apply C:\Users\YOHANM~1\AppData\Local\Temp\tmp-9876VqVaNS6q4UJl\file.patch
error: patch failed: .eslintrc.js:20
error: .eslintrc.js: patch does not apply
error: patch failed: package.json:19
error: package.json: patch does not apply

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.run (C:\dev\blahblahblah\marketplace-front\node_modules\git-diff-apply\src\run.js:8:19)
    at applyDiff (C:\dev\blahblahblah\marketplace-front\node_modules\git-diff-apply\src\index.js:121:13)
    at copy.then (C:\dev\blahblahblah\marketplace-front\node_modules\git-diff-apply\src\index.js:206:7)
    at <anonymous>:null:null
    at process._tickCallback (internal/process/next_tick.js:188:7)


=================================================================================
```

**Comment by kellyselden** [comment]
Do you get the same result when running the global command?

**Comment by yohanmishkin** [comment]
Yeah, looks like the same error message (perhaps formatted a tiny bit differently).

**Comment by kellyselden** [comment]
I use this all the time on Windows without issue. Maybe your hunch about it being your machine is correct. Either way, I can't think of any way to make progress on this. Perhaps a public repo that I can reproduce on? Please report back, and we can reopen.

**Comment by yohanmishkin** [comment]
Sounds great, thanks @kellyselden !
