### ISSUE TITLE
Doesn't play nicely with pre-commit

### ISSUE THREAD

**Issue by jrjohnson** [ember-cli/ember-cli-update#332]
We use [pre-commit](https://www.npmjs.com/package/pre-commit) to run some code linting before each commit which seems to throw off the update process since `node_modules` isn't around.

```
git-diff-apply git commit -m "message" +0ms
git/hooks/pre-commit: line 2: ./node_modules/pre-commit/hook: No such file or directory
```

I think adding `--no-verify` to (what I think is an) interim commit would fix this and wouldn't break anything else, but I wasn't able to really determine where that would go.

```
$ DEBUG=ember-cli-update,git-diff-apply ember-cli-update
  ember-cli-update npm info ember-cli versions --json +0ms
  ember-cli-update [
  ember-cli-update   "0.0.0",
  ember-cli-update   "0.0.1",
  ember-cli-update   "0.0.2",
  ember-cli-update   "0.0.3",
  ember-cli-update   "0.0.4",
  ember-cli-update   "0.0.5",
  ember-cli-update   "0.0.6",
  ember-cli-update   "0.0.7",
  ember-cli-update   "0.0.8",
  ember-cli-update   "0.0.9",
  ember-cli-update   "0.0.10",
  ember-cli-update   "0.0.11",
  ember-cli-update   "0.0.12",
  ember-cli-update   "0.0.13",
  ember-cli-update   "0.0.14",
  ember-cli-update   "0.0.15",
  ember-cli-update   "0.0.16",
  ember-cli-update   "0.0.18",
  ember-cli-update   "0.0.19",
  ember-cli-update   "0.0.20",
  ember-cli-update   "0.0.21",
  ember-cli-update   "0.0.22",
  ember-cli-update   "0.0.23",
  ember-cli-update   "0.0.24",
  ember-cli-update   "0.0.25",
  ember-cli-update   "0.0.27",
  ember-cli-update   "0.0.28",
  ember-cli-update   "0.0.29",
  ember-cli-update   "0.0.32",
  ember-cli-update   "0.0.33",
  ember-cli-update   "0.0.34",
  ember-cli-update   "0.0.35",
  ember-cli-update   "0.0.36",
  ember-cli-update   "0.0.37",
  ember-cli-update   "0.0.38",
  ember-cli-update   "0.0.39",
  ember-cli-update   "0.0.40",
  ember-cli-update   "0.0.41",
  ember-cli-update   "0.0.42",
  ember-cli-update   "0.0.43",
  ember-cli-update   "0.0.44",
  ember-cli-update   "0.0.45",
  ember-cli-update   "0.0.46",
  ember-cli-update   "0.0.47",
  ember-cli-update   "0.1.0",
  ember-cli-update   "0.1.1",
  ember-cli-update   "0.1.2",
  ember-cli-update   "0.1.3",
  ember-cli-update   "0.1.4",
  ember-cli-update   "0.1.5",
  ember-cli-update   "0.1.6",
  ember-cli-update   "0.1.7",
  ember-cli-update   "0.1.8",
  ember-cli-update   "0.1.9",
  ember-cli-update   "0.1.10",
  ember-cli-update   "0.1.11",
  ember-cli-update   "0.1.12",
  ember-cli-update   "0.1.13",
  ember-cli-update   "0.1.14",
  ember-cli-update   "0.1.15",
  ember-cli-update   "0.2.0-beta.1",
  ember-cli-update   "0.2.0",
  ember-cli-update   "0.2.1",
  ember-cli-update   "0.2.2",
  ember-cli-update   "0.2.3",
  ember-cli-update   "0.2.4",
  ember-cli-update   "0.2.5",
  ember-cli-update   "0.2.6",
  ember-cli-update   "0.2.7",
  ember-cli-update   "1.13.0",
  ember-cli-update   "1.13.1",
  ember-cli-update   "1.13.5",
  ember-cli-update   "1.13.6",
  ember-cli-update   "1.13.7",
  ember-cli-update   "1.13.8",
  ember-cli-update   "1.13.9",
  ember-cli-update   "1.13.10",
  ember-cli-update   "1.13.11",
  ember-cli-update   "1.13.12",
  ember-cli-update   "1.13.13",
  ember-cli-update   "1.13.14",
  ember-cli-update   "1.13.15",
  ember-cli-update   "2.2.0-beta.1",
  ember-cli-update   "2.2.0-beta.2",
  ember-cli-update   "2.2.0-beta.3",
  ember-cli-update   "2.2.0-beta.4",
  ember-cli-update   "2.2.0-beta.5",
  ember-cli-update   "2.2.0-beta.6",
  ember-cli-update   "2.3.0-beta.1",
  ember-cli-update   "2.3.0-beta.2",
  ember-cli-update   "2.3.0",
  ember-cli-update   "2.4.0",
  ember-cli-update   "2.4.1",
  ember-cli-update   "2.4.2",
  ember-cli-update   "2.4.3",
  ember-cli-update   "2.5.0",
  ember-cli-update   "2.5.1",
  ember-cli-update   "2.6.0-beta.1",
  ember-cli-update   "2.6.0-beta.2",
  ember-cli-update   "2.6.0-beta.3",
  ember-cli-update   "2.6.0",
  ember-cli-update   "2.6.1",
  ember-cli-update   "2.6.2",
  ember-cli-update   "2.6.3",
  ember-cli-update   "2.7.0-beta.1",
  ember-cli-update   "2.7.0-beta.2",
  ember-cli-update   "2.7.0-beta.3",
  ember-cli-update   "2.7.0-beta.4",
  ember-cli-update   "2.7.0-beta.5",
  ember-cli-update   "2.7.0-beta.6",
  ember-cli-update   "2.7.0",
  ember-cli-update   "2.8.0-beta.1",
  ember-cli-update   "2.8.0-beta.2",
  ember-cli-update   "2.8.0-beta.3",
  ember-cli-update   "2.8.0",
  ember-cli-update   "2.9.0-beta.1",
  ember-cli-update   "2.9.0-beta.2",
  ember-cli-update   "2.9.0",
  ember-cli-update   "2.9.1",
  ember-cli-update   "2.10.0-beta.1",
  ember-cli-update   "2.10.0-beta.2",
  ember-cli-update   "2.10.0",
  ember-cli-update   "2.10.1",
  ember-cli-update   "2.11.0-beta.1",
  ember-cli-update   "2.11.0-beta.2",
  ember-cli-update   "2.11.0",
  ember-cli-update   "2.11.1",
  ember-cli-update   "2.12.0-beta.1",
  ember-cli-update   "2.12.0-beta.2",
  ember-cli-update   "2.12.0",
  ember-cli-update   "2.12.1",
  ember-cli-update   "2.12.2",
  ember-cli-update   "2.12.3",
  ember-cli-update   "2.13.0-beta.1",
  ember-cli-update   "2.13.0-beta.2",
  ember-cli-update   "2.13.0-beta.3",
  ember-cli-update   "2.13.0-beta.4",
  ember-cli-update   "2.13.0",
  ember-cli-update   "2.13.1",
  ember-cli-update   "2.13.2",
  ember-cli-update   "2.13.3",
  ember-cli-update   "2.14.0-beta.1",
  ember-cli-update   "2.14.0-beta.2",
  ember-cli-update   "2.14.0",
  ember-cli-update   "2.14.1",
  ember-cli-update   "2.14.2",
  ember-cli-update   "2.15.0-beta.1",
  ember-cli-update   "2.15.0-beta.2",
  ember-cli-update   "2.15.0",
  ember-cli-update   "2.15.1",
  ember-cli-update   "2.16.0-beta.1",
  ember-cli-update   "2.16.0-beta.2",
  ember-cli-update   "2.16.0",
  ember-cli-update   "2.16.1",
  ember-cli-update   "2.16.2",
  ember-cli-update   "2.17.0-beta.1",
  ember-cli-update   "2.17.0-beta.2",
  ember-cli-update   "2.17.0",
  ember-cli-update   "2.17.1",
  ember-cli-update   "2.17.2",
  ember-cli-update   "2.18.0-beta.1",
  ember-cli-update   "2.18.0-beta.2",
  ember-cli-update   "2.18.0",
  ember-cli-update   "2.18.1",
  ember-cli-update   "2.18.2",
  ember-cli-update   "3.0.0-beta.1",
  ember-cli-update   "3.0.0-beta.2",
  ember-cli-update   "3.0.0",
  ember-cli-update   "3.0.1",
  ember-cli-update   "3.0.2",
  ember-cli-update   "3.0.3",
  ember-cli-update   "3.0.4",
  ember-cli-update   "3.1.0-beta.1",
  ember-cli-update   "3.1.0",
  ember-cli-update   "3.1.1",
  ember-cli-update   "3.1.2",
  ember-cli-update   "3.1.3",
  ember-cli-update   "3.1.4",
  ember-cli-update   "3.2.0-beta.1",
  ember-cli-update   "3.2.0-beta.2"
  ember-cli-update ]
  ember-cli-update  +1s
  ember-cli-update npm info ember-cli@latest version --json +4ms
  ember-cli-update "3.1.4"
  ember-cli-update  +538ms
  git-diff-apply git status --porcelain +0ms
  git-diff-apply  +446ms
  git-diff-apply git clone --mirror https://github.com/ember-cli/ember-new-output /var/folders/67/572phq093yv84s_2xm7jhlvw0000gp/T/tmp-61460wkrxMvSnrzLK/.git +1ms
Cloning into bare repository '/var/folders/67/572phq093yv84s_2xm7jhlvw0000gp/T/tmp-61460wkrxMvSnrzLK/.git'...
  git-diff-apply  +490ms
  git-diff-apply git --git-dir="/var/folders/67/572phq093yv84s_2xm7jhlvw0000gp/T/tmp-61460wkrxMvSnrzLK/.git" rev-parse v3.1.2 +0ms
  git-diff-apply 122ae4b547a8487a426a52f58244db6822bd4092
  git-diff-apply  +14ms
  git-diff-apply git --git-dir="/var/folders/67/572phq093yv84s_2xm7jhlvw0000gp/T/tmp-61460wkrxMvSnrzLK/.git" --work-tree="/var/folders/67/572phq093yv84s_2xm7jhlvw0000gp/T/tmp-61460wkrxMvSnrzLK" checkout 122ae4b547a8487a426a52f58244db6822bd4092 +0ms
Note: checking out '122ae4b547a8487a426a52f58244db6822bd4092'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 122ae4b... 3.1.2
  git-diff-apply  +23ms
  git-diff-apply git --git-dir="/var/folders/67/572phq093yv84s_2xm7jhlvw0000gp/T/tmp-61460wkrxMvSnrzLK/.git" rev-parse v3.1.4 +3ms
  git-diff-apply 591ca782f1aeb7180a9071d2671297e6b3ad9bf3
  git-diff-apply  +16ms
  git-diff-apply git --git-dir="/var/folders/67/572phq093yv84s_2xm7jhlvw0000gp/T/tmp-61460wkrxMvSnrzLK/.git" --work-tree="/var/folders/67/572phq093yv84s_2xm7jhlvw0000gp/T/tmp-61460wkrxMvSnrzLK" checkout 591ca782f1aeb7180a9071d2671297e6b3ad9bf3 +1ms
Previous HEAD position was 122ae4b... 3.1.2
HEAD is now at 591ca78... 3.1.4
  git-diff-apply  +23ms
  git-diff-apply git rev-parse --show-toplevel +1ms
  git-diff-apply /Users/jrjohnson/Documents/code/ilios/frontend
  git-diff-apply  +14ms
  git-diff-apply git --git-dir="/var/folders/67/572phq093yv84s_2xm7jhlvw0000gp/T/tmp-61460wkrxMvSnrzLK/.git" rev-parse v3.1.2 +0ms
  git-diff-apply 122ae4b547a8487a426a52f58244db6822bd4092
  git-diff-apply  +17ms
  git-diff-apply git --git-dir="/var/folders/67/572phq093yv84s_2xm7jhlvw0000gp/T/tmp-61460wkrxMvSnrzLK/.git" --work-tree="/var/folders/67/572phq093yv84s_2xm7jhlvw0000gp/T/tmp-61460wkrxMvSnrzLK" checkout 122ae4b547a8487a426a52f58244db6822bd4092 +0ms
Previous HEAD position was 591ca78... 3.1.4
HEAD is now at 122ae4b... 3.1.2
  git-diff-apply  +24ms
  git-diff-apply chdir /Users/jrjohnson/Documents/code/ilios/frontend +0ms
  git-diff-apply git symbolic-ref --short HEAD +0ms
  git-diff-apply master
  git-diff-apply  +19ms
  git-diff-apply git checkout --orphan 2ad675e0-521c-11e8-b2a2-ebdf4668fed0 +0ms
Switched to a new branch '2ad675e0-521c-11e8-b2a2-ebdf4668fed0'
  git-diff-apply  +73ms
  git-diff-apply git reset --hard +0ms
  git-diff-apply  +185ms
  git-diff-apply ensureDirSync /Users/jrjohnson/Documents/code/ilios/frontend +277ms
  git-diff-apply chdir /Users/jrjohnson/Documents/code/ilios/frontend +1ms
  git-diff-apply [ '.editorconfig',
  git-diff-apply   '.ember-cli',
  git-diff-apply   '.eslintrc.js',
  git-diff-apply   '.git',
  git-diff-apply   '.gitignore',
  git-diff-apply   '.travis.yml',
  git-diff-apply   '.watchmanconfig',
  git-diff-apply   'README.md',
  git-diff-apply   'app',
  git-diff-apply   'config',
  git-diff-apply   'ember-cli-build.js',
  git-diff-apply   'package.json',
  git-diff-apply   'public',
  git-diff-apply   'testem.js',
  git-diff-apply   'tests',
  git-diff-apply   'vendor' ] +0ms
  git-diff-apply copy /var/folders/67/572phq093yv84s_2xm7jhlvw0000gp/T/tmp-61460wkrxMvSnrzLK /Users/jrjohnson/Documents/code/ilios/frontend +2ms
  git-diff-apply git add -A +20ms
  git-diff-apply  +20ms
  git-diff-apply git status --porcelain +0ms
  git-diff-apply A  .editorconfig
  git-diff-apply A  .ember-cli
  git-diff-apply A  .eslintrc.js
  git-diff-apply A  .gitignore
  git-diff-apply A  .travis.yml
  git-diff-apply A  .watchmanconfig
  git-diff-apply A  README.md
  git-diff-apply A  app/app.js
  git-diff-apply A  app/components/.gitkeep
  git-diff-apply A  app/controllers/.gitkeep
  git-diff-apply A  app/helpers/.gitkeep
  git-diff-apply A  app/index.html
  git-diff-apply A  app/models/.gitkeep
  git-diff-apply A  app/resolver.js
  git-diff-apply A  app/router.js
  git-diff-apply A  app/routes/.gitkeep
  git-diff-apply A  app/styles/app.css
  git-diff-apply A  app/templates/application.hbs
  git-diff-apply A  app/templates/components/.gitkeep
  git-diff-apply A  config/environment.js
  git-diff-apply A  config/targets.js
  git-diff-apply A  ember-cli-build.js
  git-diff-apply A  package.json
  git-diff-apply A  public/robots.txt
  git-diff-apply A  testem.js
  git-diff-apply A  tests/helpers/.gitkeep
  git-diff-apply A  tests/index.html
  git-diff-apply A  tests/integration/.gitkeep
  git-diff-apply A  tests/test-helper.js
  git-diff-apply A  tests/unit/.gitkeep
  git-diff-apply A  vendor/.gitkeep
  git-diff-apply  +27ms
  git-diff-apply git commit -m "message" +0ms
.git/hooks/pre-commit: line 2: ./node_modules/pre-commit/hook: No such file or directory
  git-diff-apply git clean -f +32ms
  git-diff-apply  +21ms
  git-diff-apply git checkout master +0ms
error: Your local changes to the following files would be overwritten by checkout:
	.eslintrc.js
	.gitignore
	.travis.yml
	README.md
	app/index.html
	app/router.js
	app/templates/application.hbs
	config/environment.js
	config/targets.js
	ember-cli-build.js
	package.json
	testem.js
	tests/index.html
	tests/test-helper.js
Please commit your changes or stash them before you switch branches.
Aborting
{ Error: Command failed: git checkout master
error: Your local changes to the following files would be overwritten by checkout:
	.eslintrc.js
	.gitignore
	.travis.yml
	README.md
	app/index.html
	app/router.js
	app/templates/application.hbs
	config/environment.js
	config/targets.js
	ember-cli-build.js
	package.json
	testem.js
	tests/index.html
	tests/test-helper.js
Please commit your changes or stash them before you switch branches.
Aborting

    at checkExecSyncError (child_process.js:575:11)
    at Object.execSync (child_process.js:612:13)
    at Object.run (/usr/local/lib/node_modules/ember-cli-update/node_modules/git-diff-apply/src/run.js:8:19)
    at Promise.resolve.then.then.catch.err (/usr/local/lib/node_modules/ember-cli-update/node_modules/git-diff-apply/src/index.js:247:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  status: 1,
  signal: null,
  output: 
   [ null,
     <Buffer >,
     <Buffer 65 72 72 6f 72 3a 20 59 6f 75 72 20 6c 6f 63 61 6c 20 63 68 61 6e 67 65 73 20 74 6f 20 74 68 65 20 66 6f 6c 6c 6f 77 69 6e 67 20 66 69 6c 65 73 20 77 ... > ],
  pid: 61485,
  stdout: <Buffer >,
  stderr: <Buffer 65 72 72 6f 72 3a 20 59 6f 75 72 20 6c 6f 63 61 6c 20 63 68 61 6e 67 65 73 20 74 6f 20 74 68 65 20 66 6f 6c 6c 6f 77 69 6e 67 20 66 69 6c 65 73 20 77 ... > }
```

**Comment by kellyselden** [comment]
That makes sense. It would go in https://github.com/kellyselden/git-diff-apply where the shelling out to git happens.

**Comment by kellyselden** [comment]
I see it was merged, but don't know if it made it in or not. Can you report back if it is working yet please?

**Comment by jrjohnson** [comment]
Yes, working great as of `v0.21.4`.
