### ISSUE TITLE
UnhandledPromiseRejectionWarning / windows

### ISSUE THREAD

**Issue by lifeart** [ember-cli/ember-cli-update#375]
ember-cli-update --run-codemods

v0.22.0
```
No files selected, nothing to do.
(node:21764) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Function.all (<anonymous>)
    at getAllFiles.then.then.pendingWorkers (C:\Users\lifeart\AppData\Roaming\npm-cache\_npx\19400\node_modules\ember-test-helpers-codemod\node_modules\jscodeshift\src\Runner.js:259:17)
(node:21764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:21764) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npx: installed 291 in 22.128s
Skipping path tests/acceptance which does not exist.
No files selected, nothing to do.
(node:21744) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Function.all (<anonymous>)
    at getAllFiles.then.then.pendingWorkers (C:\Users\lifeart\AppData\Roaming\npm-cache\_npx\21788\node_modules\ember-test-helpers-codemod\node_modules\jscodeshift\src\Runner.js:259:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:21744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kellyselden** [comment]
This is normal output of some of the codemods using jscodeshift. Tracking this in #109.
