### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by allthesignals** [ember-cli/ember-cli-update#453]
If you are submitting a bug report, please run your command with the debug flag:

* Unix (global): `DEBUG=ember-cli-update,git-diff-apply ember-cli-update ...`
* Windows (global): `set DEBUG=ember-cli-update,git-diff-apply && ember-cli-update ...`
* Unix (command): `DEBUG=ember-cli-update,git-diff-apply ember update ...`
* Windows (command): `set DEBUG=ember-cli-update,git-diff-apply && ember update ...`

and post the console output in the block below:

```
$ DEBUG=ember-cli-update,git-diff-apply ember-cli-update --run-codemods
  ember-cli-update npm info ember-cli versions --json +0ms
  ember-cli-update [
  ember-cli-update   "0.0.0",
  ember-cli-update   "0.0.1",
  ember-cli-update   "0.0.2",
  ember-cli-update   "0.0.3",
  ember-cli-update   "0.0.4",
  ember-cli-update   "0.0.5",
  ember-cli-update   "0.0.6",
  ember-cli-update   "0.0.7",
  ember-cli-update   "0.0.8",
  ember-cli-update   "0.0.9",
  ember-cli-update   "0.0.10",
  ember-cli-update   "0.0.11",
  ember-cli-update   "0.0.12",
  ember-cli-update   "0.0.13",
  ember-cli-update   "0.0.14",
  ember-cli-update   "0.0.15",
  ember-cli-update   "0.0.16",
  ember-cli-update   "0.0.18",
  ember-cli-update   "0.0.19",
  ember-cli-update   "0.0.20",
  ember-cli-update   "0.0.21",
  ember-cli-update   "0.0.22",
  ember-cli-update   "0.0.23",
  ember-cli-update   "0.0.24",
  ember-cli-update   "0.0.25",
  ember-cli-update   "0.0.27",
  ember-cli-update   "0.0.28",
  ember-cli-update   "0.0.29",
  ember-cli-update   "0.0.32",
  ember-cli-update   "0.0.33",
  ember-cli-update   "0.0.34",
  ember-cli-update   "0.0.35",
  ember-cli-update   "0.0.36",
  ember-cli-update   "0.0.37",
  ember-cli-update   "0.0.38",
  ember-cli-update   "0.0.39",
  ember-cli-update   "0.0.40",
  ember-cli-update   "0.0.41",
  ember-cli-update   "0.0.42",
  ember-cli-update   "0.0.43",
  ember-cli-update   "0.0.44",
  ember-cli-update   "0.0.45",
  ember-cli-update   "0.0.46",
  ember-cli-update   "0.0.47",
  ember-cli-update   "0.1.0",
  ember-cli-update   "0.1.1",
  ember-cli-update   "0.1.2",
  ember-cli-update   "0.1.3",
  ember-cli-update   "0.1.4",
  ember-cli-update   "0.1.5",
  ember-cli-update   "0.1.6",
  ember-cli-update   "0.1.7",
  ember-cli-update   "0.1.8",
  ember-cli-update   "0.1.9",
  ember-cli-update   "0.1.10",
  ember-cli-update   "0.1.11",
  ember-cli-update   "0.1.12",
  ember-cli-update   "0.1.13",
  ember-cli-update   "0.1.14",
  ember-cli-update   "0.1.15",
  ember-cli-update   "0.2.0-beta.1",
  ember-cli-update   "0.2.0",
  ember-cli-update   "0.2.1",
  ember-cli-update   "0.2.2",
  ember-cli-update   "0.2.3",
  ember-cli-update   "0.2.4",
  ember-cli-update   "0.2.5",
  ember-cli-update   "0.2.6",
  ember-cli-update   "0.2.7",
  ember-cli-update   "1.13.0",
  ember-cli-update   "1.13.1",
  ember-cli-update   "1.13.5",
  ember-cli-update   "1.13.6",
  ember-cli-update   "1.13.7",
  ember-cli-update   "1.13.8",
  ember-cli-update   "1.13.9",
  ember-cli-update   "1.13.10",
  ember-cli-update   "1.13.11",
  ember-cli-update   "1.13.12",
  ember-cli-update   "1.13.13",
  ember-cli-update   "1.13.14",
  ember-cli-update   "1.13.15",
  ember-cli-update   "2.2.0-beta.1",
  ember-cli-update   "2.2.0-beta.2",
  ember-cli-update   "2.2.0-beta.3",
  ember-cli-update   "2.2.0-beta.4",
  ember-cli-update   "2.2.0-beta.5",
  ember-cli-update   "2.2.0-beta.6",
  ember-cli-update   "2.3.0-beta.1",
  ember-cli-update   "2.3.0-beta.2",
  ember-cli-update   "2.3.0",
  ember-cli-update   "2.4.0",
  ember-cli-update   "2.4.1",
  ember-cli-update   "2.4.2",
  ember-cli-update   "2.4.3",
  ember-cli-update   "2.5.0",
  ember-cli-update   "2.5.1",
  ember-cli-update   "2.6.0-beta.1",
  ember-cli-update   "2.6.0-beta.2",
  ember-cli-update   "2.6.0-beta.3",
  ember-cli-update   "2.6.0",
  ember-cli-update   "2.6.1",
  ember-cli-update   "2.6.2",
  ember-cli-update   "2.6.3",
  ember-cli-update   "2.7.0-beta.1",
  ember-cli-update   "2.7.0-beta.2",
  ember-cli-update   "2.7.0-beta.3",
  ember-cli-update   "2.7.0-beta.4",
  ember-cli-update   "2.7.0-beta.5",
  ember-cli-update   "2.7.0-beta.6",
  ember-cli-update   "2.7.0",
  ember-cli-update   "2.8.0-beta.1",
  ember-cli-update   "2.8.0-beta.2",
  ember-cli-update   "2.8.0-beta.3",
  ember-cli-update   "2.8.0",
  ember-cli-update   "2.9.0-beta.1",
  ember-cli-update   "2.9.0-beta.2",
  ember-cli-update   "2.9.0",
  ember-cli-update   "2.9.1",
  ember-cli-update   "2.10.0-beta.1",
  ember-cli-update   "2.10.0-beta.2",
  ember-cli-update   "2.10.0",
  ember-cli-update   "2.10.1",
  ember-cli-update   "2.11.0-beta.1",
  ember-cli-update   "2.11.0-beta.2",
  ember-cli-update   "2.11.0",
  ember-cli-update   "2.11.1",
  ember-cli-update   "2.12.0-beta.1",
  ember-cli-update   "2.12.0-beta.2",
  ember-cli-update   "2.12.0",
  ember-cli-update   "2.12.1",
  ember-cli-update   "2.12.2",
  ember-cli-update   "2.12.3",
  ember-cli-update   "2.13.0-beta.1",
  ember-cli-update   "2.13.0-beta.2",
  ember-cli-update   "2.13.0-beta.3",
  ember-cli-update   "2.13.0-beta.4",
  ember-cli-update   "2.13.0",
  ember-cli-update   "2.13.1",
  ember-cli-update   "2.13.2",
  ember-cli-update   "2.13.3",
  ember-cli-update   "2.14.0-beta.1",
  ember-cli-update   "2.14.0-beta.2",
  ember-cli-update   "2.14.0",
  ember-cli-update   "2.14.1",
  ember-cli-update   "2.14.2",
  ember-cli-update   "2.15.0-beta.1",
  ember-cli-update   "2.15.0-beta.2",
  ember-cli-update   "2.15.0",
  ember-cli-update   "2.15.1",
  ember-cli-update   "2.16.0-beta.1",
  ember-cli-update   "2.16.0-beta.2",
  ember-cli-update   "2.16.0",
  ember-cli-update   "2.16.1",
  ember-cli-update   "2.16.2",
  ember-cli-update   "2.17.0-beta.1",
  ember-cli-update   "2.17.0-beta.2",
  ember-cli-update   "2.17.0",
  ember-cli-update   "2.17.1",
  ember-cli-update   "2.17.2",
  ember-cli-update   "2.18.0-beta.1",
  ember-cli-update   "2.18.0-beta.2",
  ember-cli-update   "2.18.0",
  ember-cli-update   "2.18.1",
  ember-cli-update   "2.18.2",
  ember-cli-update   "3.0.0-beta.1",
  ember-cli-update   "3.0.0-beta.2",
  ember-cli-update   "3.0.0",
  ember-cli-update   "3.0.1",
  ember-cli-update   "3.0.2",
  ember-cli-update   "3.0.3",
  ember-cli-update   "3.0.4",
  ember-cli-update   "3.1.0-beta.1",
  ember-cli-update   "3.1.0",
  ember-cli-update   "3.1.1",
  ember-cli-update   "3.1.2",
  ember-cli-update   "3.1.3",
  ember-cli-update   "3.1.4",
  ember-cli-update   "3.2.0-beta.1",
  ember-cli-update   "3.2.0-beta.2",
  ember-cli-update   "3.2.0",
  ember-cli-update   "3.3.0",
  ember-cli-update   "3.4.0-beta.1",
  ember-cli-update   "3.4.0-beta.2",
  ember-cli-update   "3.4.0-beta.3",
  ember-cli-update   "3.4.1",
  ember-cli-update   "3.4.2-beta.1",
  ember-cli-update   "3.4.2",
  ember-cli-update   "3.4.3",
  ember-cli-update   "3.5.0-beta.1",
  ember-cli-update   "3.5.0-beta.2",
  ember-cli-update   "3.5.0",
  ember-cli-update   "3.5.1",
  ember-cli-update   "3.6.0-beta.1"
  ember-cli-update ]
  ember-cli-update  +926ms
  ember-cli-update npm info ember-cli@latest version --json +7ms
  ember-cli-update "3.5.1"
  ember-cli-update  +710ms
{ Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```

**Comment by kellyselden** [comment]
Judging by the answer here https://stackoverflow.com/a/20100521/1703845, you may have a unique network. Sounds like you can do `npx cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 ember-cli-update ...` to work around your network issues, but I don't think it's an issue with this repo. Please let me know if I'm wrong.

**Comment by kellyselden** [comment]
Actually, this might be a good readme entry...

**Comment by kellyselden** [comment]
@allthesignals If you can verify that my workaround fixes your issue, I will update the readme.
