### ISSUE TITLE
Error: dest already exists.

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli-update#496]
```
HEAD is now at fb844d2 2.17.0
Previous HEAD position was fb844d2 2.17.0
HEAD is now at 1bcb7a1 2.18.2
Previous HEAD position was 1bcb7a1 2.18.2
HEAD is now at fb844d2 2.17.0
Switched to a new branch 'c0807740-f491-11e8-b21e-cfbf6a666c9f'
Switched to branch 'upgrade-ember-cli-v2'
error: could not apply 312f897... message
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
Error: dest already exists.
    at pathExists (/Users/samselikoff/.npm/_npx/48212/lib/node_modules/ember-cli-update/node_modules/fs-extra/lib/move/index.js:46:31)
    at fn.apply.then.r (/Users/samselikoff/.npm/_npx/48212/lib/node_modules/ember-cli-update/node_modules/universalify/index.js:23:46)
    at <anonymous>
```

Can anyone help me reproduce?

**Comment by ASH-Michael** [comment]
@kellyselden I am facing the same issue.
Sometimes I face this error, and other times I see an EPERM error of `cannot stat` in test directories.

**Comment by k3n** [comment]
```bash
$ ember-cli-update
Cloning into bare repository '/var/folders/g8/0zbj1625217c7_wr4wsj_hp8lw0cjf/T/tmp-3074kNTktJq2LLKN/.git'...
Note: checking out 'e78fcddd4534cb1dc6efbd50bfcc0aee0b3b2b66'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at e78fcdd 2.18.2
Previous HEAD position was e78fcdd 2.18.2
HEAD is now at bea027f 3.7.1
Previous HEAD position was bea027f 3.7.1
HEAD is now at e78fcdd 2.18.2
Previous HEAD position was e78fcdd 2.18.2
HEAD is now at bea027f 3.7.1
Note: checking out 'ccbecea8934a3374febc915f360c9e8df1c50a9f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ccbecea message
Switched to a new branch 'de53fc70-3a0e-11e9-8087-057ce29586cc'
Switched to branch 'ember_upgrades'
error: could not apply 83488df0... message
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
Recorded preimage for 'packages/q2-config-ui/.eslintrc.js'
Recorded preimage for 'packages/q2-config-ui/LICENSE.md'
Recorded preimage for 'packages/q2-config-ui/README.md'
Recorded preimage for 'packages/q2-config-ui/config/ember-try.js'
Recorded preimage for 'packages/q2-config-ui/index.js'
Recorded preimage for 'packages/q2-config-ui/testem.js'
Resolved 'packages/q2-config-ui/tests/dummy/config/targets.js' using previous resolution.
{ err: undefined,
  err2: Error: dest already exists.
    at pathExists (/Users/kkendall/.nvm/versions/node/v8.11.4/lib/node_modules/ember-cli-update/node_modules/fs-extra/lib/move/index.js:46:31)
    at fn.apply.then.r (/Users/kkendall/.nvm/versions/node/v8.11.4/lib/node_modules/ember-cli-update/node_modules/universalify/index.js:23:46)
    at <anonymous> }
$ ./node_modules/.bin/ember -v
ember-cli: 2.18.2
node: 8.11.4
os: darwin x64
```

**Comment by tavosansal** [comment]
I am also getting the same error as above trying to upgrade an addon....I discovered that there were 3 files giving me issues:
.gitignore
index.js
readme.md

What I did is I took all the changes that were applied to those files after running the update command. Then ran the update command again and saw no error. Then I just reapplied the code that I had added to those files.
Not ideal at all since this could be very painful and confusing at times but it worked in the end.

**Comment by kellyselden** [comment]
> What I did is I took all the changes that were applied to those files after running the update command.

@tavosansal Can you explain? How did those files get updated if you were getting this error? Did the error not prevent your update?

**Comment by tavosansal** [comment]
@kellyselden Yeah I had more code added to the .gitignore, index.js, and readme.md, that I had added before. They were getting changed and there was a merge conflict because the update wanted to put them in their default state. I would try to resolve conflicts picking my changes where appropriate and then tried to run the update again and resulting in having a merge conflict on those files again.
So I decided to just copy the files somewhere else, try the update, pick all of the changes to make those files back to the default output, run the update again (which worked this time), and then put my code back in those files.

Hopefully this makes sense? 
Let me know if you have more questions.

**Comment by tavosansal** [comment]
OK so after doing the above ^^ ... I saw that ember 3.8 was released...so I tried to upgrade to that from 3.7.x that I was trying yesterday and I got the error again...but no conflicts happened this time... `.gitignore` added this line:
```
/.pnp*
```

And readme.md added the `Contributing` section. So I committed those changes...ran the update again...and it worked without any merge conflicts this time.

**Comment by gmkohler** [comment]
Getting this while trying to upgrade an app from 3.0 to 3.1

```
$ ember-cli-update --to 3.1
Cloning into bare repository '/var/folders/wy/qf7q4_l96jq1klnk049nssx80000gn/T/tmp-60640GabYb47B7hJa/.git'...
Note: checking out '448642d934d6155571d55421f7ea1ca229622dfa'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 448642d... 3.0.4
Previous HEAD position was 448642d... 3.0.4
HEAD is now at 75a7e8d... 3.1.4
Previous HEAD position was 75a7e8d... 3.1.4
HEAD is now at 448642d... 3.0.4
Switched to a new branch 'b6905960-409c-11e9-b03a-3fa3ef1a478f'
Switched to branch 'gmkohler/ember-3.1'
{ err: undefined,
  err2: Error: dest already exists.
    at pathExists (/Users/gregorykohler/.nvm/versions/node/v8.15.0/lib/node_modules/ember-cli-update/node_modules/fs-extra/lib/move/index.js:46:31)
    at fn.apply.then.r (/Users/gregorykohler/.nvm/versions/node/v8.15.0/lib/node_modules/ember-cli-update/node_modules/universalify/index.js:23:46)
    at <anonymous> }
```

**Comment by kellyselden** [comment]
I'm still finding it impossible to recreate. Trying to repro @gmkohler's case gives me:

```
ember-cli-update --from 3.0.4 --to 3.1
Cloning into bare repository '/var/folders/6v/2mdd4ts56x1ct5r8fv086rmh0000gn/T/tmp-35525pLb30lBO6Xi5/.git'...
Note: checking out '17e54c50330ee02236fc4b19d86ce35b0fefedd2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 17e54c5 3.0.4
Previous HEAD position was 17e54c5 3.0.4
HEAD is now at 95ae3bf 3.1.4
Previous HEAD position was 95ae3bf 3.1.4
HEAD is now at 17e54c5 3.0.4
Switched to a new branch '02f0e460-40c4-11e9-aafd-dfe8e2b3a6ff'
Switched to branch 'gmkohler/ember-3.1'
error: could not apply a14942e... message
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
```

using your versions and branch name. I'm still at a loss... Can anyone here clone this repo and try to run the test suite? Maybe that will uncover something?

**Comment by k3n** [comment]
I get consistent failures on `Integration | Index | can create a personal diff instead of using an output repo`:

https://gist.github.com/k3n/fcbc522f9654abe73638543c21b47a6a

**Comment by gmkohler** [comment]
@kellyselden The test suite is passing while using node 8.15.0 (the version I am using in my ember app) and the latest node 11 🤔

**Comment by czosel** [comment]
I've been running into the same issue, and running ember-cli-update in debug mode showed
```
  git-diff-apply [ '.CONTRIBUTING.md.swp',
  git-diff-apply   '.README.md.swp',
  git-diff-apply   '.eslintignore.swp',
  git-diff-apply   '.eslintrc.js.swp',
  git-diff-apply   '.index.js.swp',
  git-diff-apply   '.npmignore.swp',
  git-diff-apply   '.package.json.swp',
  git-diff-apply   '.travis.yml.swp',
  git-diff-apply   'config',
  git-diff-apply   'dist',
  git-diff-apply   'node_modules',
  git-diff-apply   'tmp' ] +300ms
  git-diff-apply moveAll /tmp/tmp-305934dai6Hupxtfq /home/christian/dev/ember-validated-form +0ms
{ err: undefined,
  err2:
   Error: dest already exists.
       at pathExists (/home/christian/.nvm/versions/node/v11.6.0/lib/node_modules/ember-cli-update/node_modules/fs-extra/lib/move/index.js:46:31)
       at fn.apply.then.r (/home/christian/.nvm/versions/node/v11.6.0/lib/node_modules/ember-cli-update/node_modules/universalify/index.js:23:46) }
```
Which made me check if `.swp` files might cause the issue - and indeed, removing all swap files seems to fix the issue!

After I tried to isolate the issue a little more, and it seems that the top-level swap files actually don't cause the issue. However I was able to reproduce it with just a single swap file inside my `addon` folder. In that case, the debug output was
```
  git-diff-apply [ 'addon', 'dist', 'node_modules', 'tmp' ] +149ms
  git-diff-apply moveAll /tmp/tmp-6878LvPXHuVI5AJH /home/christian/dev/ember-validated-form +0ms
{ err: undefined,
  err2:
   Error: dest already exists.
       at pathExists (/home/christian/.nvm/versions/node/v11.6.0/lib/node_modules/ember-cli-update/node_modules/fs-extra/lib/move/index.js:46:31)
       at fn.apply.then.r (/home/christian/.nvm/versions/node/v11.6.0/lib/node_modules/ember-cli-update/node_modules/universalify/index.js:23:46) }
```

I hope this helps with tracking down the issue further!

**Comment by brentzc** [comment]
I got this error updating from 3.7.1 to 3.8.1. After reseting my branch I updated ember-cli-update from 0.29.2 to 0.31.2, reran `ember-cli-update` and it worked without error. Hopefully that can be a helpful solution for someone.

**Comment by kellyselden** [comment]
@czosel When I create a .swp file, I get `You must start with a clean working directory`. I'm assuming you have a global .gitignore on .swp files?

**Comment by kellyselden** [comment]
OK I finally reproduced. @czosel Thank you!

**Comment by kellyselden** [comment]
Failing test here https://github.com/kellyselden/git-diff-apply/pull/211

**Comment by kellyselden** [comment]
Thanks to @czosel, should be fixed in v0.31.5.

**Comment by czosel** [comment]
The fix seems to work for me, thanks you @kellyselden!

**Comment by samselikoff** [comment]
Nice work!

**Comment by chrismou** [comment]
@kellyselden This still seems to be an issue for me running 0.32.2 (also tried with 0.31.5)

Any idea what I might have missed?  Or would you prefer I logged it as a new ticket?

```
Cloning into bare repository '/tmp/tmp-9653cqy24yJcWiAn/.git'...
Note: checking out 'beba5c1ef114dee100f26bfcba548598396fdbb9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at beba5c1 3.1.2
Previous HEAD position was beba5c1 3.1.2
HEAD is now at 6742bfc 3.8.1
Previous HEAD position was 6742bfc 3.8.1
HEAD is now at beba5c1 3.1.2
Switched to a new branch '4238e7b0-4c24-11e9-941c-5166454b1874'
Switched to branch 'master'
(node:9653) UnhandledPromiseRejectionWarning: Error: dest already exists.
    at pathExists (/home/mou/.nvm/versions/node/v8.11.4/lib/node_modules/ember-cli-update/node_modules/fs-extra/lib/move/index.js:46:31)
    at fn.apply.then.r (/home/mou/.nvm/versions/node/v8.11.4/lib/node_modules/ember-cli-update/node_modules/universalify/index.js:23:46)
    at <anonymous>
(node:9653) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9653) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9653) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(node:9653) UnhandledPromiseRejectionWarning: Error: dest already exists.
    at pathExists (/home/mou/.nvm/versions/node/v8.11.4/lib/node_modules/ember-cli-update/node_modules/fs-extra/lib/move/index.js:46:31)
    at fn.apply.then.r (/home/mou/.nvm/versions/node/v8.11.4/lib/node_modules/ember-cli-update/node_modules/universalify/index.js:23:46)
    at <anonymous>
(node:9653) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by gmkohler** [comment]
I ran into this again on 0.32.2 and `rm -rf tmp` fixed it

**Comment by kellyselden** [comment]
Reopening, but I don't know what the problem is. I'm trying to reproduce with tmp/ stuff.

**Comment by chrismou** [comment]
@kellyselden I managed to get it working last night on one project, by commenting out my entire `.gitignore_global` file

If it's any use, the contents is:

```
/vendor
/node_modules
/bower_components
.sass-cache
.idea/*
.vagrant/*
_ide_helper.php
.phpstorm.meta.php
.DS_Store
nohup.out
```

**Comment by kellyselden** [comment]
I fixed another /tmp bug, in v0.32.5. I don't know if it will fix this issue though.

**Comment by chrismou** [comment]
v0.32.5 has thrown up a bunch of different errors for me (worth noting that my home folder is on a separate drive). I've not had this happen before, as far as I remember.

```
HEAD is now at 6742bfc 3.8.1
Previous HEAD position was 6742bfc 3.8.1
HEAD is now at d883b7f 3.8.2
Previous HEAD position was d883b7f 3.8.2
HEAD is now at 6742bfc 3.8.1
Switched to a new branch 'b7e9aa10-5851-11e9-a4d2-b576eefd0e62'
(node:19091) UnhandledPromiseRejectionWarning: Error: EXDEV: cross-device link not permitted, rename '/home/mou/dev/project/yarn-error.log' -> '/tmp/tmp-19091NPSL6tej5ZSd/yarn-error.log'
(node:19091) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19091) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19091) UnhandledPromiseRejectionWarning: Error: EXDEV: cross-device link not permitted, rename '/home/mou/dev/project/.idea/encodings.xml' -> '/tmp/tmp-19091NPSL6tej5ZSd/.idea/encodings.xml'
(node:19091) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19091) UnhandledPromiseRejectionWarning: Error: EXDEV: cross-device link not permitted, rename '/home/mou/dev/project/.idea/jsLibraryMappings.xml' -> '/tmp/tmp-19091NPSL6tej5ZSd/.idea/jsLibraryMappings.xml'
(node:19091) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```
... 225 times, and then...
```
(node:19091) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```
Another 225 times. And ends with:
```
Switched to branch 'master'
{ Error: EXDEV: cross-device link not permitted, rename '/home/mou/dev/project/yarn-error.log' -> '/tmp/tmp-19091NPSL6tej5ZSd/yarn-error.log'
  errno: -18,
  code: 'EXDEV',
  syscall: 'rename',
  path: '/home/mou/dev/project/yarn-error.log',
  dest: '/tmp/tmp-19091NPSL6tej5ZSd/yarn-error.log' }
```

Can log this in another ticket if you prefer

**Comment by fpauser** [comment]
Same problem here, trying to upgrade an addon with ember-cli-update@0.32.5 on a system with a separate home partition:

```
$ ecu
Klone in Bare-Repository '/tmp/tmp-16785p62pzADjiluQ/.git' ...
Hinweis: Checke '76cf2103459d7095844d0efa4af6efc84317a11a' aus.

Sie befinden sich im Zustand eines 'losgelösten HEAD'. Sie können sich
umschauen, experimentelle Änderungen vornehmen und diese committen, und
Sie können alle möglichen Commits, die Sie in diesem Zustand machen,
ohne Auswirkungen auf irgendeinen Branch verwerfen, indem Sie einen
weiteren Checkout durchführen.

Wenn Sie einen neuen Branch erstellen möchten, um Ihre erstellten Commits
zu behalten, können Sie das (jetzt oder später) durch einen weiteren Checkout
mit der Option -b tun. Beispiel:

  git checkout -b <neuer-Branchname>

HEAD ist jetzt bei 76cf210 3.8.1
Vorherige Position von HEAD war 76cf210 3.8.1
HEAD ist jetzt bei 659ab3d 3.9.0
Vorherige Position von HEAD war 659ab3d 3.9.0
HEAD ist jetzt bei 76cf210 3.8.1
Zu neuem Branch 'e2eafda0-5c24-11e9-84ee-7b4a624f5754' gewechselt
(node:16785) UnhandledPromiseRejectionWarning: Error: EXDEV: cross-device link not permitted, rename '/home/fpauser/dev/vasig/phx/phx-core/jsconfig.json' -> '/tmp/tmp-16785MgBaorCC5Ipq/jsconfig.json'
(node:16785) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16785) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Zu Branch 'master' gewechselt
{ [Error: EXDEV: cross-device link not permitted, rename '/home/fpauser/dev/vasig/phx/phx-core/jsconfig.json' -> '/tmp/tmp-16785MgBaorCC5Ipq/jsconfig.json']
  errno: -18,
  code: 'EXDEV',
  syscall: 'rename',
  path: '/home/fpauser/dev/vasig/phx/phx-core/jsconfig.json',
  dest: '/tmp/tmp-16785MgBaorCC5Ipq/jsconfig.json' }
(node:16785) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)

```

**Comment by kellyselden** [comment]
EXDEV stuff is tracked here #549

**Comment by kellyselden** [comment]
With the recent changes to git-diff-apply, is this still an issue after reinstalling ember-cli-update?

**Comment by chrismou** [comment]
The good news is it fixed the cross-device error.  But unfortunately, I'm now back here:

  ```
HEAD is now at c27feca 3.8.2
Previous HEAD position was c27feca 3.8.2
HEAD is now at 659ab3d 3.9.0
Previous HEAD position was 659ab3d 3.9.0
HEAD is now at c27feca 3.8.2
Switched to a new branch '544c9f70-5c44-11e9-b804-951f905bc37f'
Switched to branch 'master'
(node:2677) UnhandledPromiseRejectionWarning: Error: dest already exists.
    at pathExists (/path/to/project/node_modules/fs-extra/lib/move/index.js:46:31)
    at fn.apply.then.r (/path/to/project/node_modules/universalify/index.js:23:46)
    at <anonymous>
(node:2677) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2677) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2677) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
{ err: undefined,
  err2: Error: dest already exists.
    at pathExists (/path/to/project/node_modules/fs-extra/lib/move/index.js:46:31)
    at fn.apply.then.r (/path/to/project/node_modules/universalify/index.js:23:46)
    at <anonymous> }
```

**Comment by bneill2** [comment]
also seeing this issue

`HEAD is now at 7574857 2.15.0
Previous HEAD position was 7574857 2.15.0
HEAD is now at 1cc6d33 2.16.0
Previous HEAD position was 1cc6d33 2.16.0
HEAD is now at 7574857 2.15.0
Switched to a new branch '5c41ac20-5d52-11e9-889a-9f463318216b'
Switched to branch 'develop-ember-latest'
error: could not apply 21ec710... message
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
(node:6763) UnhandledPromiseRejectionWarning: Error: dest already exists.
    at pathExists (/Users/bneill/.nvm/versions/node/v11.14.0/lib/node_modules/ember-cli-update/node_modules/fs-extra/lib/move/index.js:46:31)
    at fn.apply.then.r (/Users/bneill/.nvm/versions/node/v11.14.0/lib/node_modules/ember-cli-update/node_modules/universalify/index.js:23:46)
(node:6763) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6763) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ err: undefined,
  err2:
   Error: dest already exists.
       at pathExists (/Users/bneill/.nvm/versions/node/v11.14.0/lib/node_modules/ember-cli-update/node_modules/fs-extra/lib/move/index.js:46:31)
       at fn.apply.then.r (/Users/bneill/.nvm/versions/node/v11.14.0/lib/node_modules/ember-cli-update/node_modules/universalify/index.js:23:46) }
(node:6763) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)`

**Comment by stevenchendan** [comment]
I face exactly the same issue you posted while I upgrade from 2.17 to 2.18 yesterday.
My ember-cli-update version is 0.34.7
My ember-cli version 2.17.0

This is my package.json information hope this can help you reproduce it:

    "ember-ajax": "^3.0.0",
    "ember-bootstrap": "^1.0.0-rc.5",
    "ember-cli": "~2.17.0",
    "ember-cli-accounting": "^2.0.2",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.6.0",
    "ember-cli-dependency-checker": "^2.0.0",
    "ember-cli-eslint": "^4.2.1",
    "ember-cli-google-recaptcha": "^2.3.0",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-less": "^1.5.5",
    "ember-cli-moment-shim": "^3.5.0",
    "ember-cli-qunit": "^4.1.1",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^2.0.0",
    "ember-d3": "^0.4.4",
    "ember-data": "~2.17.0",
    "ember-export-application-global": "^2.0.0",
    "ember-fetch": "^3.4.4",
    "ember-highcharts": "^1.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-metrics": "^0.12.1",
    "ember-models-table": "^2.2.3",
    "ember-moment": "^7.5.0",
    "ember-radio-button": "^1.2.1",
    "ember-resolver": "^4.0.0",
    "ember-simple-auth": "^1.4.0",
    "ember-source": "~2.17.0",
    "ember-toggle": "^5.3.2",
    "ember-truth-helpers": "^2.0.0",
    "ember-useragent": "^0.6.1",
    "ember-weakmap": "^3.2.0",
    "ember-welcome-page": "^3.0.0",

**Comment by kellyselden** [comment]
I got this again. In ember-aframe. It made most the changes, but the package.json change was missing. Resetting and trying again made it work. Still not sure what's wrong.

```
(node:17509) UnhandledPromiseRejectionWarning: Error: dest already exists.
    at /Users/kselden/.volta/tools/image/packages/ember-cli-update/0.47.1/node_modules/fs-extra/lib/move/move.js:41:31
    at /Users/kselden/.volta/tools/image/packages/ember-cli-update/0.47.1/node_modules/universalify/index.js:23:46
```

**Comment by kellyselden** [comment]
This probably isn't an issue anymore with v0.49.0.
