### ISSUE TITLE
ERR_CHILD_PROCESS_STDIO_MAXBUFFER

### ISSUE THREAD

**Issue by loginovma** [ember-cli/ember-cli-update#583]
Got this when running ember-cli-update --to 3.10.1 in large monorepo.

```
{ RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:348:14)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
  cmd: 'git ls-files',
  stdout: '-long-string-with-filenames-here-'
```

**Comment by robclancy** [comment]
Yep just went to update and got this.

**Comment by robclancy** [comment]
I was able to fix it by changing this:

https://github.com/kellyselden/git-diff-apply/blob/47ff095ca65f81e7ceae698666a52908f79222a2/src/git-remove-all.js#L12

```js
let files = (await run('git ls-files', Object.assign({ maxBuffer: 1024 * 500 }, options))).trim().split(/\r?\n/g);
```

**Comment by michaelst** [comment]
I am also running into this same issue

**Comment by tfazekas** [comment]
> I was able to fix it by changing this:
> 
> https://github.com/kellyselden/git-diff-apply/blob/47ff095ca65f81e7ceae698666a52908f79222a2/src/git-remove-all.js#L12
> 
> ```js
> let files = (await run('git ls-files', Object.assign({ maxBuffer: 1024 * 500 }, options))).trim().split(/\r?\n/g);
> ```

Could you tell what cause the problem and how you resolved this?
Haven't found anything related to git-diff-apply
I have the same issue,  but don't really know what should I change or which file.
Thanks

**Comment by koopa** [comment]
@tfazekas I was just looking for this myself, maybe this helps:
`cd $(npm list -g | head -n1)/node_modules/ember-cli-update/node_modules/git-diff-apply`

**Comment by tfazekas** [comment]
@koopa 
Thanks koopa!

**Comment by kellyselden** [comment]
I used @robclancy's suggestion. Can you try with v0.34.13 and report back?

**Comment by bryanhickerson** [comment]
I still have this issue as of 0.43.6.

```
$ ember-cli-update --to "3.11.0"
{ RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:354:14)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:265:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
  cmd: 'git commit -m "message" --no-verify',
$ ember-cli-update --version
0.43.6
```

**Comment by bryanhickerson** [comment]
>I still have this issue as of 0.43.6.

Issue didn't happen in the upgrade from 3.11 to 3.12

**Comment by timiyay** [comment]
We've just encountered this error when also running in a large Ember monorepo.

@kellyselden WDYT about maxing the `maxBuffer` into a CLI param for `ember-cli-update`?

That would free us up to experiment with a maxBuffer size that suits our repo, while allowing you to maintain sensible defaults.

If that sounds agreeable, I can get a PR together.

**Comment by timiyay** [comment]
I've since seen the `git-diff-apply` PR that switches to `spawn` to, theoretically, sidestep any max buffer issues: https://github.com/kellyselden/git-diff-apply/pull/278.

Unfortunately, we're still encountering the max buffer issue, when attempting to upgrade from Ember 3.10 to 3.11.

ember-cli-update: 0.47.1
nodejs: 10.15.0

```
{ RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:348:14)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
  cmd: 'git commit -m "message" --no-verify',
  stdout: 'very-large-showstopping-output',
  stderr: ''
}
```

**Comment by kellyselden** [comment]
@timiyay I think first step would be to get it to match the other spawn fix, then worry about configuring later. Thanks.

**Comment by timiyay** [comment]
@DeclanBoller has opened the relevant PR against `git-diff-apply` here: https://github.com/kellyselden/git-diff-apply/pull/295

**Comment by kellyselden** [comment]
This probably isn't an issue anymore with v0.49.0.

**Comment by Benjy1979** [comment]
I've got this issue again in Version 3.1.1 (x64)
`2022-10-17T00:41:57.311Z - info: [ui] [BranchPruner] Last prune took place 2 hours ago - skipping
2022-10-17T00:41:59.227Z - error: [ui] Could not load old contents for syntax highlighting
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at Socket.onChildStdout (node:child_process:470:14)
    at Socket.emit (node:events:538:35)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)`
