### ISSUE TITLE
.gitignore_global not being considered?

### ISSUE THREAD

**Issue by MichalBryxi** [ember-cli/ember-cli-update#695]
```
~/Projects/kasa/ui/frontend maint/update-backend
❯ DEBUG=ember-cli-update,boilerplate-update,git-diff-apply ember-cli-update
  git-diff-apply npm view ember-cli versions --json +0ms
  git-diff-apply [
  git-diff-apply   "0.0.0",
  git-diff-apply   "0.0.1",
  git-diff-apply   "0.0.2",
  git-diff-apply   "0.0.3",
  git-diff-apply   "0.0.4",
  git-diff-apply   "0.0.5",
  git-diff-apply   "0.0.6",
  git-diff-apply   "0.0.7",
  git-diff-apply   "0.0.8",
  git-diff-apply   "0.0.9",
  git-diff-apply   "0.0.10",
  git-diff-apply   "0.0.11",
  git-diff-apply   "0.0.12",
  git-diff-apply   "0.0.13",
  git-diff-apply   "0.0.14",
  git-diff-apply   "0.0.15",
  git-diff-apply   "0.0.16",
  git-diff-apply   "0.0.18",
  git-diff-apply   "0.0.19",
  git-diff-apply   "0.0.20",
  git-diff-apply   "0.0.21",
  git-diff-apply   "0.0.22",
  git-diff-apply   "0.0.23",
  git-diff-apply   "0.0.24",
  git-diff-apply   "0.0.25",
  git-diff-apply   "0.0.27",
  git-diff-apply   "0.0.28",
  git-diff-apply   "0.0.29",
  git-diff-apply   "0.0.32",
  git-diff-apply   "0.0.33",
  git-diff-apply   "0.0.34",
  git-diff-apply   "0.0.35",
  git-diff-apply   "0.0.36",
  git-diff-apply   "0.0.37",
  git-diff-apply   "0.0.38",
  git-diff-apply   "0.0.39",
  git-diff-apply   "0.0.40",
  git-diff-apply   "0.0.41",
  git-diff-apply   "0.0.42",
  git-diff-apply   "0.0.43",
  git-diff-apply   "0.0.44",
  git-diff-apply   "0.0.45",
  git-diff-apply   "0.0.46",
  git-diff-apply   "0.0.47",
  git-diff-apply   "0.1.0",
  git-diff-apply   "0.1.1",
  git-diff-apply   "0.1.2",
  git-diff-apply   "0.1.3",
  git-diff-apply   "0.1.4",
  git-diff-apply   "0.1.5",
  git-diff-apply   "0.1.6",
  git-diff-apply   "0.1.7",
  git-diff-apply   "0.1.8",
  git-diff-apply   "0.1.9",
  git-diff-apply   "0.1.10",
  git-diff-apply   "0.1.11",
  git-diff-apply   "0.1.12",
  git-diff-apply   "0.1.13",
  git-diff-apply   "0.1.14",
  git-diff-apply   "0.1.15",
  git-diff-apply   "0.2.0-beta.1",
  git-diff-apply   "0.2.0",
  git-diff-apply   "0.2.1",
  git-diff-apply   "0.2.2",
  git-diff-apply   "0.2.3",
  git-diff-apply   "0.2.4",
  git-diff-apply   "0.2.5",
  git-diff-apply   "0.2.6",
  git-diff-apply   "0.2.7",
  git-diff-apply   "1.13.0",
  git-diff-apply   "1.13.1",
  git-diff-apply   "1.13.5",
  git-diff-apply   "1.13.6",
  git-diff-apply   "1.13.7",
  git-diff-apply   "1.13.8",
  git-diff-apply   "1.13.9",
  git-diff-apply   "1.13.10",
  git-diff-apply   "1.13.11",
  git-diff-apply   "1.13.12",
  git-diff-apply   "1.13.13",
  git-diff-apply   "1.13.14",
  git-diff-apply   "1.13.15",
  git-diff-apply   "2.2.0-beta.1",
  git-diff-apply   "2.2.0-beta.2",
  git-diff-apply   "2.2.0-beta.3",
  git-diff-apply   "2.2.0-beta.4",
  git-diff-apply   "2.2.0-beta.5",
  git-diff-apply   "2.2.0-beta.6",
  git-diff-apply   "2.3.0-beta.1",
  git-diff-apply   "2.3.0-beta.2",
  git-diff-apply   "2.3.0",
  git-diff-apply   "2.4.0",
  git-diff-apply   "2.4.1",
  git-diff-apply   "2.4.2",
  git-diff-apply   "2.4.3",
  git-diff-apply   "2.5.0",
  git-diff-apply   "2.5.1",
  git-diff-apply   "2.6.0-beta.1",
  git-diff-apply   "2.6.0-beta.2",
  git-diff-apply   "2.6.0-beta.3",
  git-diff-apply   "2.6.0",
  git-diff-apply   "2.6.1",
  git-diff-apply   "2.6.2",
  git-diff-apply   "2.6.3",
  git-diff-apply   "2.7.0-beta.1",
  git-diff-apply   "2.7.0-beta.2",
  git-diff-apply   "2.7.0-beta.3",
  git-diff-apply   "2.7.0-beta.4",
  git-diff-apply   "2.7.0-beta.5",
  git-diff-apply   "2.7.0-beta.6",
  git-diff-apply   "2.7.0",
  git-diff-apply   "2.8.0-beta.1",
  git-diff-apply   "2.8.0-beta.2",
  git-diff-apply   "2.8.0-beta.3",
  git-diff-apply   "2.8.0",
  git-diff-apply   "2.9.0-beta.1",
  git-diff-apply   "2.9.0-beta.2",
  git-diff-apply   "2.9.0",
  git-diff-apply   "2.9.1",
  git-diff-apply   "2.10.0-beta.1",
  git-diff-apply   "2.10.0-beta.2",
  git-diff-apply   "2.10.0",
  git-diff-apply   "2.10.1",
  git-diff-apply   "2.11.0-beta.1",
  git-diff-apply   "2.11.0-beta.2",
  git-diff-apply   "2.11.0",
  git-diff-apply   "2.11.1",
  git-diff-apply   "2.12.0-beta.1",
  git-diff-apply   "2.12.0-beta.2",
  git-diff-apply   "2.12.0",
  git-diff-apply   "2.12.1",
  git-diff-apply   "2.12.2",
  git-diff-apply   "2.12.3",
  git-diff-apply   "2.13.0-beta.1",
  git-diff-apply   "2.13.0-beta.2",
  git-diff-apply   "2.13.0-beta.3",
  git-diff-apply   "2.13.0-beta.4",
  git-diff-apply   "2.13.0",
  git-diff-apply   "2.13.1",
  git-diff-apply   "2.13.2",
  git-diff-apply   "2.13.3",
  git-diff-apply   "2.14.0-beta.1",
  git-diff-apply   "2.14.0-beta.2",
  git-diff-apply   "2.14.0",
  git-diff-apply   "2.14.1",
  git-diff-apply   "2.14.2",
  git-diff-apply   "2.15.0-beta.1",
  git-diff-apply   "2.15.0-beta.2",
  git-diff-apply   "2.15.0",
  git-diff-apply   "2.15.1",
  git-diff-apply   "2.16.0-beta.1",
  git-diff-apply   "2.16.0-beta.2",
  git-diff-apply   "2.16.0",
  git-diff-apply   "2.16.1",
  git-diff-apply   "2.16.2",
  git-diff-apply   "2.17.0-beta.1",
  git-diff-apply   "2.17.0-beta.2",
  git-diff-apply   "2.17.0",
  git-diff-apply   "2.17.1",
  git-diff-apply   "2.17.2",
  git-diff-apply   "2.18.0-beta.1",
  git-diff-apply   "2.18.0-beta.2",
  git-diff-apply   "2.18.0",
  git-diff-apply   "2.18.1",
  git-diff-apply   "2.18.2",
  git-diff-apply   "3.0.0-beta.1",
  git-diff-apply   "3.0.0-beta.2",
  git-diff-apply   "3.0.0",
  git-diff-apply   "3.0.1",
  git-diff-apply   "3.0.2",
  git-diff-apply   "3.0.3",
  git-diff-apply   "3.0.4",
  git-diff-apply   "3.1.0-beta.1",
  git-diff-apply   "3.1.0",
  git-diff-apply   "3.1.1",
  git-diff-apply   "3.1.2",
  git-diff-apply   "3.1.3",
  git-diff-apply   "3.1.4",
  git-diff-apply   "3.2.0-beta.1",
  git-diff-apply   "3.2.0-beta.2",
  git-diff-apply   "3.2.0",
  git-diff-apply   "3.3.0",
  git-diff-apply   "3.4.0-beta.1",
  git-diff-apply   "3.4.0-beta.2",
  git-diff-apply   "3.4.0-beta.3",
  git-diff-apply   "3.4.1",
  git-diff-apply   "3.4.2-beta.1",
  git-diff-apply   "3.4.2",
  git-diff-apply   "3.4.3",
  git-diff-apply   "3.4.4",
  git-diff-apply   "3.5.0-beta.1",
  git-diff-apply   "3.5.0-beta.2",
  git-diff-apply   "3.5.0",
  git-diff-apply   "3.5.1",
  git-diff-apply   "3.6.0-beta.1",
  git-diff-apply   "3.6.0",
  git-diff-apply   "3.6.1",
  git-diff-apply   "3.7.0-beta.1",
  git-diff-apply   "3.7.0-beta.2",
  git-diff-apply   "3.7.0",
  git-diff-apply   "3.7.1",
  git-diff-apply   "3.8.0-beta.1",
  git-diff-apply   "3.8.0",
  git-diff-apply   "3.8.1",
  git-diff-apply   "3.8.2",
  git-diff-apply   "3.8.3",
  git-diff-apply   "3.9.0-beta.1",
  git-diff-apply   "3.9.0-beta.2",
  git-diff-apply   "3.9.0",
  git-diff-apply   "3.10.0-beta.1",
  git-diff-apply   "3.10.0-beta.2",
  git-diff-apply   "3.10.0",
  git-diff-apply   "3.10.1",
  git-diff-apply   "3.11.0-beta.1",
  git-diff-apply   "3.11.0-beta.3",
  git-diff-apply   "3.11.0",
  git-diff-apply   "3.12.0",
  git-diff-apply   "3.13.0-beta.1"
  git-diff-apply ]
  git-diff-apply  +902ms
  git-diff-apply git status --porcelain +8ms
  git-diff-apply git clone --mirror https://github.com/ember-cli/ember-new-output /var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO/.git +24ms
  git-diff-apply  +1s
  git-diff-apply git --git-dir="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO/.git" rev-parse v3.4.3 +0ms
  git-diff-apply 1f612533c12dfe8cc669787f2fede2a18afa062f
  git-diff-apply  +14ms
  git-diff-apply git --git-dir="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO/.git" --work-tree="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO" checkout 1f612533c12dfe8cc669787f2fede2a18afa062f +0ms
  git-diff-apply  +23ms
  git-diff-apply git --git-dir="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO/.git" rev-parse v3.12.0 +3ms
  git-diff-apply 1f07601f8618ff896c35552b510be79be6c6996d
  git-diff-apply  +13ms
  git-diff-apply git --git-dir="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO/.git" --work-tree="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO" checkout 1f07601f8618ff896c35552b510be79be6c6996d +1ms
  git-diff-apply  +32ms
  git-diff-apply git rev-parse --show-toplevel +1ms
  git-diff-apply /Users/mbryxi/Projects/kasa
  git-diff-apply  +17ms
  git-diff-apply git init +1ms
  git-diff-apply Initialized empty Git repository in /private/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714yaQZ9Jf57yph/.git/
  git-diff-apply  +25ms
  git-diff-apply git config user.email "you@example.com" +0ms
  git-diff-apply  +24ms
  git-diff-apply git config user.name "Your Name" +0ms
  git-diff-apply  +15ms
  git-diff-apply git config --local core.excludesfile false +0ms
  git-diff-apply  +15ms
  git-diff-apply ensureDir /var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714yaQZ9Jf57yph/ui/frontend +0ms
  git-diff-apply git --git-dir="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO/.git" rev-parse v3.4.3 +1ms
  git-diff-apply 1f612533c12dfe8cc669787f2fede2a18afa062f
  git-diff-apply  +14ms
  git-diff-apply git --git-dir="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO/.git" --work-tree="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO" checkout 1f612533c12dfe8cc669787f2fede2a18afa062f +0ms
  git-diff-apply  +26ms
  git-diff-apply [ '.editorconfig',
  git-diff-apply   '.ember-cli',
  git-diff-apply   '.eslintignore',
  git-diff-apply   '.eslintrc.js',
  git-diff-apply   '.git',
  git-diff-apply   '.gitignore',
  git-diff-apply   '.template-lintrc.js',
  git-diff-apply   '.travis.yml',
  git-diff-apply   '.watchmanconfig',
  git-diff-apply   'README.md',
  git-diff-apply   'app',
  git-diff-apply   'config',
  git-diff-apply   'ember-cli-build.js',
  git-diff-apply   'package.json',
  git-diff-apply   'public',
  git-diff-apply   'testem.js',
  git-diff-apply   'tests',
  git-diff-apply   'vendor' ] +0ms
  git-diff-apply copy /var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO /var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714yaQZ9Jf57yph/ui/frontend +14ms
  git-diff-apply git add -A +36ms
  git-diff-apply  +32ms
  git-diff-apply git status --porcelain +0ms
  git-diff-apply git commit -m "message" --no-verify +13ms
  git-diff-apply [master (root-commit) d495415] message
  git-diff-apply  34 files changed, 477 insertions(+)
  git-diff-apply  create mode 100644 ui/frontend/.editorconfig
  git-diff-apply  create mode 100644 ui/frontend/.ember-cli
  git-diff-apply  create mode 100644 ui/frontend/.eslintignore
  git-diff-apply  create mode 100644 ui/frontend/.eslintrc.js
  git-diff-apply  create mode 100644 ui/frontend/.gitignore
  git-diff-apply  create mode 100644 ui/frontend/.template-lintrc.js
  git-diff-apply  create mode 100644 ui/frontend/.travis.yml
  git-diff-apply  create mode 100644 ui/frontend/.watchmanconfig
  git-diff-apply  create mode 100644 ui/frontend/README.md
  git-diff-apply  create mode 100644 ui/frontend/app/app.js
  git-diff-apply  create mode 100644 ui/frontend/app/components/.gitkeep
  git-diff-apply  create mode 100644 ui/frontend/app/controllers/.gitkeep
  git-diff-apply  create mode 100644 ui/frontend/app/helpers/.gitkeep
  git-diff-apply  create mode 100644 ui/frontend/app/index.html
  git-diff-apply  create mode 100644 ui/frontend/app/models/.gitkeep
  git-diff-apply  create mode 100644 ui/frontend/app/resolver.js
  git-diff-apply  create mode 100644 ui/frontend/app/router.js
  git-diff-apply  create mode 100644 ui/frontend/app/routes/.gitkeep
  git-diff-apply  create mode 100644 ui/frontend/app/styles/app.css
  git-diff-apply  create mode 100644 ui/frontend/app/templates/application.hbs
  git-diff-apply  create mode 100644 ui/frontend/app/templates/components/.gitkeep
  git-diff-apply  create mode 100644 ui/frontend/config/environment.js
  git-diff-apply  create mode 100644 ui/frontend/config/optional-features.json
  git-diff-apply  create mode 100644 ui/frontend/config/targets.js
  git-diff-apply  create mode 100644 ui/frontend/ember-cli-build.js
  git-diff-apply  create mode 100644 ui/frontend/package.json
  git-diff-apply  create mode 100644 ui/frontend/public/robots.txt
  git-diff-apply  create mode 100644 ui/frontend/testem.js
  git-diff-apply  create mode 100644 ui/frontend/tests/helpers/.gitkeep
  git-diff-apply  create mode 100644 ui/frontend/tests/index.html
  git-diff-apply  create mode 100644 ui/frontend/tests/integration/.gitkeep
  git-diff-apply  create mode 100644 ui/frontend/tests/test-helper.js
  git-diff-apply  create mode 100644 ui/frontend/tests/unit/.gitkeep
  git-diff-apply  create mode 100644 ui/frontend/vendor/.gitkeep
  git-diff-apply  +35ms
  git-diff-apply git tag v3.4.3 +0ms
  git-diff-apply  +14ms
  git-diff-apply git ls-files +1ms
  git-diff-apply git add ui/frontend/.editorconfig ui/frontend/.ember-cli ui/frontend/.eslintignore ui/frontend/.eslintrc.js ui/frontend/.gitignore ui/frontend/.template-lintrc.js ui/frontend/.travis.yml ui/frontend/.watchmanconfig ui/frontend/README.md ui/frontend/app/app.js ui/frontend/app/components/.gitkeep ui/frontend/app/controllers/.gitkeep ui/frontend/app/helpers/.gitkeep ui/frontend/app/index.html ui/frontend/app/models/.gitkeep ui/frontend/app/resolver.js ui/frontend/app/router.js ui/frontend/app/routes/.gitkeep ui/frontend/app/styles/app.css ui/frontend/app/templates/application.hbs ui/frontend/app/templates/components/.gitkeep ui/frontend/config/environment.js ui/frontend/config/optional-features.json ui/frontend/config/targets.js ui/frontend/ember-cli-build.js ui/frontend/package.json ui/frontend/public/robots.txt ui/frontend/testem.js ui/frontend/tests/helpers/.gitkeep ui/frontend/tests/index.html ui/frontend/tests/integration/.gitkeep ui/frontend/tests/test-helper.js ui/frontend/tests/unit/.gitkeep ui/frontend/vendor/.gitkeep +17ms
  git-diff-apply ensureDir /var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714yaQZ9Jf57yph/ui/frontend +202ms
  git-diff-apply git --git-dir="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO/.git" rev-parse v3.12.0 +13ms
  git-diff-apply 1f07601f8618ff896c35552b510be79be6c6996d
  git-diff-apply  +14ms
  git-diff-apply git --git-dir="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO/.git" --work-tree="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO" checkout 1f07601f8618ff896c35552b510be79be6c6996d +0ms
  git-diff-apply  +20ms
  git-diff-apply [ '.editorconfig',
  git-diff-apply   '.ember-cli',
  git-diff-apply   '.eslintignore',
  git-diff-apply   '.eslintrc.js',
  git-diff-apply   '.git',
  git-diff-apply   '.gitignore',
  git-diff-apply   '.template-lintrc.js',
  git-diff-apply   '.travis.yml',
  git-diff-apply   '.watchmanconfig',
  git-diff-apply   'README.md',
  git-diff-apply   'app',
  git-diff-apply   'config',
  git-diff-apply   'ember-cli-build.js',
  git-diff-apply   'package.json',
  git-diff-apply   'public',
  git-diff-apply   'testem.js',
  git-diff-apply   'tests',
  git-diff-apply   'vendor' ] +180ms
  git-diff-apply copy /var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714vo4FAy6y4hkO /var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714yaQZ9Jf57yph/ui/frontend +1ms
  git-diff-apply git add -A +15ms
  git-diff-apply  +21ms
  git-diff-apply git status --porcelain +0ms
  git-diff-apply git commit -m "message" --no-verify +22ms
  git-diff-apply [master 54cbdad] message
  git-diff-apply  8 files changed, 40 insertions(+), 30 deletions(-)
  git-diff-apply  +30ms
  git-diff-apply git tag v3.12.0 +1ms
  git-diff-apply  +17ms
  git-diff-apply git --git-dir="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714yaQZ9Jf57yph/.git" rev-parse v3.4.3 +0ms
  git-diff-apply d495415df81c4f93bcb356d777aca4d7aa34e13c
  git-diff-apply  +18ms
  git-diff-apply git --git-dir="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714yaQZ9Jf57yph/.git" --work-tree="/var/folders/dw/bx1n948x7bgdmwdpxgns8q040000gn/T/tmp-15714yaQZ9Jf57yph" checkout d495415df81c4f93bcb356d777aca4d7aa34e13c +0ms
  git-diff-apply  +22ms
  git-diff-apply git symbolic-ref --short HEAD +0ms
  git-diff-apply maint/update-backend
  git-diff-apply  +13ms
  git-diff-apply git checkout --orphan 3e17fc50-d240-11e9-b7ce-0570147eabd9 +1ms
  git-diff-apply  +27ms
  git-diff-apply git ls-files +1ms
  git-diff-apply git add .dockerignore .env .gitignore .gitlab-ci.yml .vscode/settings.json CHANGELOG.cs.md README.md ...[LONG LIST OF FILES WAS HERE]... +45ms
  git-diff-apply git checkout maint/update-backend +17ms
  git-diff-apply  +51ms
Error: git add .dockerignore .env .gitignore .gitlab-ci.yml .vscode/settings.json CHANGELOG.cs.md README.md ...[LONG LIST OF FILES WAS HERE] ... failed with message The following paths are ignored by one of your .gitignore files:
.vscode
Use -f if you really want to add them.

    at ChildProcess.<anonymous> (/Users/mbryxi/.config/yarn/global/node_modules/git-diff-apply/src/run.js:34:16)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

~/Projects/kasa/ui/frontend maint/update-backend
❯
```

I think the problem will be in: 

```
❯ cat ~/.gitignore_global
*~
.DS_Store
jsconfig.json
.vscode/
```

Namely the `.vscode` directory being mentioned in my global `~/.gitignore_global` file that contributes to repository `.gitignore` calculcations.

To get path to users `~/.gitignore_global`:

```
❯ git config --get core.excludesfile
/Users/mbryxi/.gitignore_global
```

Originally I thought this was resolved in #111, but seems like I bumped into other edge-case.

**Comment by kellyselden** [comment]
I remember fixes this a while ago. Not sure what's up this time.

**Comment by kellyselden** [comment]
This probably isn't an issue anymore with v0.49.0.
