### ISSUE TITLE
Files error when using ember-auto-import dynamic imports

### ISSUE THREAD

**Issue by benmurden** [ember-cli/ember-cli-update#726]
## Dynamic imports

https://github.com/ef4/ember-auto-import#dynamic-import

Environment is Windows 10.

```
 ERR app\components\my-component.js Transformation error
SyntaxError: 'import' and 'export' may only appear at the top level (15:4)
    at Parser.pp.raise (C:\Users\Benjamin\AppData\Roaming\npm\node_modules\ember-modules-codemod\node_modules\babel-core\node_modules\babylon\lib\parser\location.js:24:13)
    at Parser.pp.parseStatement (C:\Users\Benjamin\AppData\Roaming\npm\node_modules\ember-modules-codemod\node_modules\babel-core\node_modules\babylon\lib\parser\statement.js:111:29)
    at Parser.parseStatement (C:\Users\Benjamin\AppData\Roaming\npm\node_modules\ember-modules-codemod\node_modules\babel-core\node_modules\babylon\lib\plugins\flow.js:655:22)
    at Parser.pp.parseBlock (C:\Users\Benjamin\AppData\Roaming\npm\node_modules\ember-modules-codemod\node_modules\babel-core\node_modules\babylon\lib\parser\statement.js:442:21)
    at Parser.pp.parseFunctionBody (C:\Users\Benjamin\AppData\Roaming\npm\node_modules\ember-modules-codemod\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:747:22)
    at Parser.parseFunctionBody (C:\Users\Benjamin\AppData\Roaming\npm\node_modules\ember-modules-codemod\node_modules\babel-core\node_modules\babylon\lib\plugins\flow.js:643:20)
    at Parser.pp.parseMethod (C:\Users\Benjamin\AppData\Roaming\npm\node_modules\ember-modules-codemod\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:717:8)
    at Parser.pp.parseObjPropValue (C:\Users\Benjamin\AppData\Roaming\npm\node_modules\ember-modules-codemod\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:658:23)
    at Parser.parseObjPropValue (C:\Users\Benjamin\AppData\Roaming\npm\node_modules\ember-modules-codemod\node_modules\babel-core\node_modules\babylon\lib\plugins\flow.js:891:13)
    at Parser.pp.parseObj (C:\Users\Benjamin\AppData\Roaming\npm\node_modules\ember-modules-codemod\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:640:10)
```

**Comment by kellyselden** [comment]
This is probably an issue with one of the codemods you ran. It should have displayed in the console. If it's not already fixed, this issue should be moved to that project. Thanks for filing.
