### ISSUE TITLE
--reset + --create-custom-diff doesn't work

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli-update#733]
```
$ ember-cli-update --create-custom-diff --reset
Error: Command failed: git tag v3.13.1
fatal: tag 'v3.13.1' already exists

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1028:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 128,
  signal: null,
  cmd: 'git tag v3.13.1',
  stdout: '',
  stderr: "fatal: tag 'v3.13.1' already exists\n"
}
```

**Comment by kellyselden** [comment]
only affects you if you're already on latest version.
