### ISSUE TITLE
ember-cli-update blows away my git history

### ISSUE THREAD

**Issue by dustinsoftware** [ember-cli/ember-cli-update#759]
When running `ember-cli-update@0.45.0` on my app, it crashes part way through and breaks the local git history and reflog. My app is currently using ember 3.12. I suspect that because `git config --global core.autocrlf` is enabled in the current workspace, that is not playing nicely with checkout commands.  Disabling `autocrlf` seems to be a workaround.

Running various git commands shows no reflog anymore:
```
user@3c2e4754592c:/app$ git status
On branch 0bc20600-0bc1-11ea-9f24-4f519db74542

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        app/
        config/
        e2e/
        node_modules/
        public/
        tests/
        vendor/

nothing added to commit but untracked files present (use "git add" to track)
user@3c2e4754592c:/app$ git reflog
fatal: your current branch '0bc20600-0bc1-11ea-9f24-4f519db74542' does not have any commits yet
```

If you are submitting a bug report, please run your command with the debug flag:

* Unix (global): `DEBUG=ember-cli-update,boilerplate-update,git-diff-apply ember-cli-update ...`
* Windows (global): `set DEBUG=ember-cli-update,boilerplate-update,git-diff-apply && ember-cli-update ...`
* Unix (command): `DEBUG=ember-cli-update,boilerplate-update,git-diff-apply ember update ...`
* Windows (command): `set DEBUG=ember-cli-update,boilerplate-update,git-diff-apply && ember update ...`

and post the console output in the block below:

```
user@b36e1c2c8730:/app$ DEBUG=ember-cli-update,boilerplate-update,git-diff-apply ~/.config/yarn/global/node_modules/.bin/ember-cli-update                 
  git-diff-apply npm view ember-cli versions --json +0ms
  git-diff-apply [
  git-diff-apply   "0.0.0",
  git-diff-apply   "0.0.1",
  git-diff-apply   "0.0.2",
  git-diff-apply   "0.0.3",
  git-diff-apply   "0.0.4",
  git-diff-apply   "0.0.5",
  git-diff-apply   "0.0.6",
  git-diff-apply   "0.0.7",
  git-diff-apply   "0.0.8",
  git-diff-apply   "0.0.9",
  git-diff-apply   "0.0.10",
  git-diff-apply   "0.0.11",
  git-diff-apply   "0.0.12",
  git-diff-apply   "0.0.13",
  git-diff-apply   "0.0.14",
  git-diff-apply   "0.0.15",
  git-diff-apply   "0.0.16",
  git-diff-apply   "0.0.18",
  git-diff-apply   "0.0.19",
  git-diff-apply   "0.0.20",
  git-diff-apply   "0.0.21",
  git-diff-apply   "0.0.22",
  git-diff-apply   "0.0.23",
  git-diff-apply   "0.0.24",
  git-diff-apply   "0.0.25",
  git-diff-apply   "0.0.27",
  git-diff-apply   "0.0.28",
  git-diff-apply   "0.0.29",
  git-diff-apply   "0.0.32",
  git-diff-apply   "0.0.33",
  git-diff-apply   "0.0.34",
  git-diff-apply   "0.0.35",
  git-diff-apply   "0.0.36",
  git-diff-apply   "0.0.37",
  git-diff-apply   "0.0.38",
  git-diff-apply   "0.0.39",
  git-diff-apply   "0.0.40",
  git-diff-apply   "0.0.41",
  git-diff-apply   "0.0.42",
  git-diff-apply   "0.0.43",
  git-diff-apply   "0.0.44",
  git-diff-apply   "0.0.45",
  git-diff-apply   "0.0.46",
  git-diff-apply   "0.0.47",
  git-diff-apply   "0.1.0",
  git-diff-apply   "0.1.1",
  git-diff-apply   "0.1.2",
  git-diff-apply   "0.1.3",
  git-diff-apply   "0.1.4",
  git-diff-apply   "0.1.5",
  git-diff-apply   "0.1.6",
  git-diff-apply   "0.1.7",
  git-diff-apply   "0.1.8",
  git-diff-apply   "0.1.9",
  git-diff-apply   "0.1.10",
  git-diff-apply   "0.1.11",
  git-diff-apply   "0.1.12",
  git-diff-apply   "0.1.13",
  git-diff-apply   "0.1.14",
  git-diff-apply   "0.1.15",
  git-diff-apply   "0.2.0-beta.1",
  git-diff-apply   "0.2.0",
  git-diff-apply   "0.2.1",
  git-diff-apply   "0.2.2",
  git-diff-apply   "0.2.3",
  git-diff-apply   "0.2.4",
  git-diff-apply   "0.2.5",
  git-diff-apply   "0.2.6",
  git-diff-apply   "0.2.7",
  git-diff-apply   "1.13.0",
  git-diff-apply   "1.13.1",
  git-diff-apply   "1.13.5",
  git-diff-apply   "1.13.6",
  git-diff-apply   "1.13.7",
  git-diff-apply   "1.13.8",
  git-diff-apply   "1.13.9",
  git-diff-apply   "1.13.10",
  git-diff-apply   "1.13.11",
  git-diff-apply   "1.13.12",
  git-diff-apply   "1.13.13",
  git-diff-apply   "1.13.14",
  git-diff-apply   "1.13.15",
  git-diff-apply   "2.2.0-beta.1",
  git-diff-apply   "2.2.0-beta.2",
  git-diff-apply   "2.2.0-beta.3",
  git-diff-apply   "2.2.0-beta.4",
  git-diff-apply   "2.2.0-beta.5",
  git-diff-apply   "2.2.0-beta.6",
  git-diff-apply   "2.3.0-beta.1",
  git-diff-apply   "2.3.0-beta.2",
  git-diff-apply   "2.3.0",
  git-diff-apply   "2.4.0",
  git-diff-apply   "2.4.1",
  git-diff-apply   "2.4.2",
  git-diff-apply   "2.4.3",
  git-diff-apply   "2.5.0",
  git-diff-apply   "2.5.1",
  git-diff-apply   "2.6.0-beta.1",
  git-diff-apply   "2.6.0-beta.2",
  git-diff-apply   "2.6.0-beta.3",
  git-diff-apply   "2.6.0",
  git-diff-apply   "2.6.1",
  git-diff-apply   "2.6.2",
  git-diff-apply   "2.6.3",
  git-diff-apply   "2.7.0-beta.1",
  git-diff-apply   "2.7.0-beta.2",
  git-diff-apply   "2.7.0-beta.3",
  git-diff-apply   "2.7.0-beta.4",
  git-diff-apply   "2.7.0-beta.5",
  git-diff-apply   "2.7.0-beta.6",
  git-diff-apply   "2.7.0",
  git-diff-apply   "2.8.0-beta.1",
  git-diff-apply   "2.8.0-beta.2",
  git-diff-apply   "2.8.0-beta.3",
  git-diff-apply   "2.8.0",
  git-diff-apply   "2.9.0-beta.1",
  git-diff-apply   "2.9.0-beta.2",
  git-diff-apply   "2.9.0",
  git-diff-apply   "2.9.1",
  git-diff-apply   "2.10.0-beta.1",
  git-diff-apply   "2.10.0-beta.2",
  git-diff-apply   "2.10.0",
  git-diff-apply   "2.10.1",
  git-diff-apply   "2.11.0-beta.1",
  git-diff-apply   "2.11.0-beta.2",
  git-diff-apply   "2.11.0",
  git-diff-apply   "2.11.1",
  git-diff-apply   "2.12.0-beta.1",
  git-diff-apply   "2.12.0-beta.2",
  git-diff-apply   "2.12.0",
  git-diff-apply   "2.12.1",
  git-diff-apply   "2.12.2",
  git-diff-apply   "2.12.3",
  git-diff-apply   "2.13.0-beta.1",
  git-diff-apply   "2.13.0-beta.2",
  git-diff-apply   "2.13.0-beta.3",
  git-diff-apply   "2.13.0-beta.4",
  git-diff-apply   "2.13.0",
  git-diff-apply   "2.13.1",
  git-diff-apply   "2.13.2",
  git-diff-apply   "2.13.3",
  git-diff-apply   "2.14.0-beta.1",
  git-diff-apply   "2.14.0-beta.2",
  git-diff-apply   "2.14.0",
  git-diff-apply   "2.14.1",
  git-diff-apply   "2.14.2",
  git-diff-apply   "2.15.0-beta.1",
  git-diff-apply   "2.15.0-beta.2",
  git-diff-apply   "2.15.0",
  git-diff-apply   "2.15.1",
  git-diff-apply   "2.16.0-beta.1",
  git-diff-apply   "2.16.0-beta.2",
  git-diff-apply   "2.16.0",
  git-diff-apply   "2.16.1",
  git-diff-apply   "2.16.2",
  git-diff-apply   "2.17.0-beta.1",
  git-diff-apply   "2.17.0-beta.2",
  git-diff-apply   "2.17.0",
  git-diff-apply   "2.17.1",
  git-diff-apply   "2.17.2",
  git-diff-apply   "2.18.0-beta.1",
  git-diff-apply   "2.18.0-beta.2",
  git-diff-apply   "2.18.0",
  git-diff-apply   "2.18.1",
  git-diff-apply   "2.18.2",
  git-diff-apply   "3.0.0-beta.1",
  git-diff-apply   "3.0.0-beta.2",
  git-diff-apply   "3.0.0",
  git-diff-apply   "3.0.1",
  git-diff-apply   "3.0.2",
  git-diff-apply   "3.0.3",
  git-diff-apply   "3.0.4",
  git-diff-apply   "3.1.0-beta.1",
  git-diff-apply   "3.1.0",
  git-diff-apply   "3.1.1",
  git-diff-apply   "3.1.2",
  git-diff-apply   "3.1.3",
  git-diff-apply   "3.1.4",
  git-diff-apply   "3.2.0-beta.1",
  git-diff-apply   "3.2.0-beta.2",
  git-diff-apply   "3.2.0",
  git-diff-apply   "3.3.0",
  git-diff-apply   "3.4.0-beta.1",
  git-diff-apply   "3.4.0-beta.2",
  git-diff-apply   "3.4.0-beta.3",
  git-diff-apply   "3.4.1",
  git-diff-apply   "3.4.2-beta.1",
  git-diff-apply   "3.4.2",
  git-diff-apply   "3.4.3",
  git-diff-apply   "3.4.4",
  git-diff-apply   "3.5.0-beta.1",
  git-diff-apply   "3.5.0-beta.2",
  git-diff-apply   "3.5.0",
  git-diff-apply   "3.5.1",
  git-diff-apply   "3.6.0-beta.1",
  git-diff-apply   "3.6.0",
  git-diff-apply   "3.6.1",
  git-diff-apply   "3.7.0-beta.1",
  git-diff-apply   "3.7.0-beta.2",
  git-diff-apply   "3.7.0",
  git-diff-apply   "3.7.1",
  git-diff-apply   "3.8.0-beta.1",
  git-diff-apply   "3.8.0",
  git-diff-apply   "3.8.1",
  git-diff-apply   "3.8.2",
  git-diff-apply   "3.8.3",
  git-diff-apply   "3.9.0-beta.1",
  git-diff-apply   "3.9.0-beta.2",
  git-diff-apply   "3.9.0",
  git-diff-apply   "3.10.0-beta.1",
  git-diff-apply   "3.10.0-beta.2",
  git-diff-apply   "3.10.0",
  git-diff-apply   "3.10.1",
  git-diff-apply   "3.11.0-beta.1",
  git-diff-apply   "3.11.0-beta.3",
  git-diff-apply   "3.11.0",
  git-diff-apply   "3.12.0",
  git-diff-apply   "3.13.0-beta.1",
  git-diff-apply   "3.13.0",
  git-diff-apply   "3.13.1",
  git-diff-apply   "3.13.2",
  git-diff-apply   "3.14.0-beta.1",
  git-diff-apply   "3.14.0-beta.2",
  git-diff-apply   "3.14.0",
  git-diff-apply   "3.15.0-beta.1"
  git-diff-apply ]
  git-diff-apply  +619ms
  git-diff-apply git status --porcelain +8ms
  git-diff-apply git clone --mirror https://github.com/ember-cli/ember-new-output /tmp/tmp-5843E1rTWWhcie0/.git +19ms
  git-diff-apply  +1s
  git-diff-apply git --git-dir="/tmp/tmp-5843E1rTWWhcie0/.git" rev-parse v3.12.0 +1ms
  git-diff-apply 1f07601f8618ff896c35552b510be79be6c6996d
  git-diff-apply  +4ms
  git-diff-apply git --git-dir="/tmp/tmp-5843E1rTWWhcie0/.git" --work-tree="/tmp/tmp-5843E1rTWWhcie0" checkout 1f07601f8618ff896c35552b510be79be6c6996d +0ms
  git-diff-apply  +6ms
  git-diff-apply git --git-dir="/tmp/tmp-5843E1rTWWhcie0/.git" rev-parse v3.14.0 +3ms
  git-diff-apply f803abff78df5317bc438a60025c581b063428c1
  git-diff-apply  +4ms
  git-diff-apply git --git-dir="/tmp/tmp-5843E1rTWWhcie0/.git" --work-tree="/tmp/tmp-5843E1rTWWhcie0" checkout f803abff78df5317bc438a60025c581b063428c1 +0ms
  git-diff-apply  +8ms
  git-diff-apply git rev-parse --show-toplevel +1ms
  git-diff-apply /app
  git-diff-apply  +5ms
  git-diff-apply git --git-dir="/tmp/tmp-5843E1rTWWhcie0/.git" rev-parse v3.12.0 +0ms
  git-diff-apply 1f07601f8618ff896c35552b510be79be6c6996d
  git-diff-apply  +4ms
  git-diff-apply git --git-dir="/tmp/tmp-5843E1rTWWhcie0/.git" --work-tree="/tmp/tmp-5843E1rTWWhcie0" checkout 1f07601f8618ff896c35552b510be79be6c6996d +0ms
  git-diff-apply  +7ms
  git-diff-apply git symbolic-ref --short HEAD +0ms
  git-diff-apply ember-3-14
  git-diff-apply  +5ms
  git-diff-apply git checkout --orphan 2a48be00-0bc3-11ea-8bbd-9f3fb8b798f8 +0ms
  git-diff-apply  +22ms
  git-diff-apply git ls-files +0ms
  git-diff-apply git add REDACTED web-client.sublime-project yarn.lock +24ms
  git-diff-apply [ '.git',
  git-diff-apply   '.github',
  git-diff-apply   '.vscode',
  git-diff-apply   'app',
  git-diff-apply   'blueprints',
  git-diff-apply   'config',
  git-diff-apply   'dist',
  git-diff-apply   'e2e',
  git-diff-apply   'jsconfig.json',
  git-diff-apply   'ladrs',
  git-diff-apply   'lib',
  git-diff-apply   'mirage',
  git-diff-apply   'node_modules',
  git-diff-apply   'public',
  git-diff-apply   'rfcs',
  git-diff-apply   'scripts',
  git-diff-apply   'supervisord.log',
  git-diff-apply   'supervisord.pid',
  git-diff-apply   'tests',
  git-diff-apply   'tmp',
  git-diff-apply   'translations',
  git-diff-apply   'types',
  git-diff-apply   'vendor' ] +0ms
  git-diff-apply mergeDir /app /tmp/tmp-584Jc2SZuxZ83gT +1ms
  git-diff-apply from /app +2ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT +0ms
  git-diff-apply from /app/.github +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/.github +0ms
  git-diff-apply from /app/.vscode +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/.vscode +0ms
  git-diff-apply from /app/app +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app +0ms
  git-diff-apply from /app/blueprints +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/blueprints +0ms
  git-diff-apply from /app/config +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/config +0ms
  git-diff-apply from /app/dist +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/dist +1ms
  git-diff-apply from /app/e2e +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/e2e +0ms
  git-diff-apply from /app/jsconfig.json +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/jsconfig.json +0ms
  git-diff-apply from /app/ladrs +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/ladrs +0ms
  git-diff-apply from /app/lib +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/lib +0ms
  git-diff-apply from /app/mirage +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/mirage +0ms
  git-diff-apply from /app/public +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/public +0ms
  git-diff-apply from /app/rfcs +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/rfcs +0ms
  git-diff-apply from /app/scripts +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/scripts +0ms
  git-diff-apply from /app/supervisord.log +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/supervisord.log +0ms
  git-diff-apply from /app/supervisord.pid +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/supervisord.pid +0ms
  git-diff-apply from /app/tests +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/tests +0ms
  git-diff-apply from /app/tmp +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/tmp +0ms
  git-diff-apply from /app/translations +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/translations +0ms
  git-diff-apply from /app/types +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types +0ms
  git-diff-apply from /app/vendor +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/vendor +0ms
  git-diff-apply from /app/app/adapters +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/adapters +1ms
  git-diff-apply from /app/app/components +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/components +0ms
  git-diff-apply from /app/app/config +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/config +0ms
  git-diff-apply from /app/app/controllers +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/controllers +1ms
  git-diff-apply from /app/app/decorators +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/decorators +0ms
  git-diff-apply from /app/app/helpers +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/helpers +0ms
  git-diff-apply from /app/app/initializers +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/initializers +0ms
  git-diff-apply from /app/app/instance-initializers +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/instance-initializers +0ms
  git-diff-apply from /app/app/lib +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/lib +0ms
  git-diff-apply from /app/app/mixins +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/mixins +0ms
  git-diff-apply from /app/app/models +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/models +0ms
  git-diff-apply from /app/app/routes +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/routes +0ms
  git-diff-apply from /app/app/serializers +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/serializers +0ms
  git-diff-apply from /app/app/services +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/services +0ms
  git-diff-apply from /app/app/styles +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/styles +0ms
  git-diff-apply from /app/app/templates +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/templates +0ms
  git-diff-apply from /app/app/transforms +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/app/transforms +0ms
  git-diff-apply from /app/blueprints/responsive-component +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/blueprints/responsive-component +0ms
  git-diff-apply from /app/blueprints/route-component +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/blueprints/route-component +0ms
  git-diff-apply from /app/dist/assets +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/dist/assets +0ms
  git-diff-apply from /app/dist/ember-fetch +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/dist/ember-fetch +0ms
  git-diff-apply from /app/dist/fonts +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/dist/fonts +0ms
  git-diff-apply from /app/dist/heap +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/dist/heap +0ms
  git-diff-apply from /app/dist/img +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/dist/img +0ms
  git-diff-apply from /app/dist/index.html +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/dist/index.html +0ms
  git-diff-apply from /app/dist/responsive +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/dist/responsive +0ms
  git-diff-apply from /app/dist/robots.txt +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/dist/robots.txt +0ms
  git-diff-apply from /app/e2e/test +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/e2e/test +0ms
  git-diff-apply from /app/e2e/types +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/e2e/types +0ms
  git-diff-apply from /app/e2e/utils +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/e2e/utils +0ms
  git-diff-apply from /app/lib/ember-cli-deploy-json-config-revision +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/lib/ember-cli-deploy-json-config-revision +0ms
  git-diff-apply from /app/lib/freestyle +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/lib/freestyle +0ms
  git-diff-apply from /app/mirage/data +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/mirage/data +0ms
  git-diff-apply from /app/mirage/endpoints +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/mirage/endpoints +0ms
  git-diff-apply from /app/mirage/factories +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/mirage/factories +1ms
  git-diff-apply from /app/mirage/fixtures +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/mirage/fixtures +0ms
  git-diff-apply from /app/mirage/helpers +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/mirage/helpers +0ms
  git-diff-apply from /app/mirage/scenarios +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/mirage/scenarios +0ms
  git-diff-apply from /app/public/assets +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/public/assets +0ms
  git-diff-apply from /app/public/fonts +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/public/fonts +0ms
  git-diff-apply from /app/public/heap +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/public/heap +0ms
  git-diff-apply from /app/public/img +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/public/img +0ms
  git-diff-apply from /app/public/responsive +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/public/responsive +0ms
  git-diff-apply from /app/rfcs/imgs +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/rfcs/imgs +0ms
  git-diff-apply from /app/tests/acceptance +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/tests/acceptance +0ms
  git-diff-apply from /app/tests/components +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/tests/components +0ms
  git-diff-apply from /app/tests/helpers +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/tests/helpers +0ms
  git-diff-apply from /app/tests/integration +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/tests/integration +0ms
  git-diff-apply from /app/tests/unit +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/tests/unit +0ms
  git-diff-apply from /app/types/ember-a11y-testing +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/ember-a11y-testing +0ms
  git-diff-apply from /app/types/ember-ajax +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/ember-ajax +0ms
  git-diff-apply from /app/types/ember-basic-dropdown +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/ember-basic-dropdown +0ms
  git-diff-apply from /app/types/ember-cli-mirage +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/ember-cli-mirage +0ms
  git-diff-apply from /app/types/ember-cli-qunit +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/ember-cli-qunit +0ms
  git-diff-apply from /app/types/ember-data-url-templates +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/ember-data-url-templates +0ms
  git-diff-apply from /app/types/ember-exam +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/ember-exam +0ms
  git-diff-apply from /app/types/ember-fetch +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/ember-fetch +0ms
  git-diff-apply from /app/types/ember-freestyle +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/ember-freestyle +0ms
  git-diff-apply from /app/types/ember-intl +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/ember-intl +0ms
  git-diff-apply from /app/types/ember-load-initializers +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/ember-load-initializers +0ms
  git-diff-apply from /app/types/ember-responsive +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/ember-responsive +0ms
  git-diff-apply from /app/types/ember-text-mask +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/ember-text-mask +0ms
  git-diff-apply from /app/types/mixpanel-browser +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/mixpanel-browser +0ms
  git-diff-apply from /app/types/mobile-web +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/types/mobile-web +0ms
  git-diff-apply from /app/vendor/clamp-js +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/vendor/clamp-js +0ms
  git-diff-apply from /app/vendor/olo +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/vendor/olo +0ms
  git-diff-apply from /app/vendor/polyfills +0ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/vendor/polyfills +0ms
  git-diff-apply from /app/vendor/raygun +1ms
  git-diff-apply to /tmp/tmp-584Jc2SZuxZ83gT/vendor/raygun +0ms
  git-diff-apply from /app/app/components/customize +0ms
  git-diff-apply REDACTED/r-post-checkout +1ms
  git-diff-apply [ '.editorconfig',
  git-diff-apply   '.ember-cli',
  git-diff-apply   '.eslintignore',
  git-diff-apply   '.eslintrc.js',
  git-diff-apply   '.git',
  git-diff-apply   '.gitignore',
  git-diff-apply   '.template-lintrc.js',
  git-diff-apply   '.travis.yml',
  git-diff-apply   '.watchmanconfig',
  git-diff-apply   'README.md',
  git-diff-apply   'app',
  git-diff-apply   'config',
  git-diff-apply   'ember-cli-build.js',
  git-diff-apply   'package.json',
  git-diff-apply   'public',
  git-diff-apply   'testem.js',
  git-diff-apply   'tests',
  git-diff-apply   'vendor' ] +0ms
  git-diff-apply copy /tmp/tmp-5843E1rTWWhcie0 /app +0ms
  git-diff-apply git add -A +1s
  git-diff-apply git clean -f +465ms
  git-diff-apply Removing .editorconfig
  git-diff-apply Removing .ember-cli
  git-diff-apply Removing .eslintignore
  git-diff-apply Removing .eslintrc.js
  git-diff-apply Removing .gitignore
  git-diff-apply Removing .template-lintrc.js
  git-diff-apply Removing .travis.yml
  git-diff-apply Removing .watchmanconfig
  git-diff-apply Removing README.md
  git-diff-apply Removing ember-cli-build.js
  git-diff-apply Removing package.json
  git-diff-apply Removing testem.js
  git-diff-apply  +8ms
  git-diff-apply git checkout ember-3-14 +0ms
{ err:
   { RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded
       at Socket.onChildStderr (child_process.js:377:14)
       at Socket.emit (events.js:198:13)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:265:13)
       at Socket.Readable.push (_stream_readable.js:224:10)
       at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
     cmd: 'git add -A',
     stdout: '',
     stderr:
      'warning: LF will be replaced by CRLF in e2e/node_modules/.yarn-integrity.\nThe file will have its original line endings in your working directory.\nwarning: LF will be replaced by CRLF in e2e/node_modules/@arr/filter/index.js.\nThe file will have its original line endings in your working directory.\nwarning: LF will be replaced by CRLF in e2e/node_modules/@arr/filter/module.js. REDACTED
```

**Comment by kellyselden** [comment]
I understand how frustrating a corrupted git repo is. This used to happen to me while I was developing this tool and fixing bugs. I haven't had this happen to me since. I'm keen on fixing it, but I don't know how. If someone could give me a reproduction, like a dummy repo on github with lots of files, I will look into it.

**Comment by kellyselden** [comment]
This probably isn't an issue anymore with v0.49.0.

**Comment by dustinsoftware** [comment]
Great! I’ll give it a go.
