### ISSUE TITLE
Improve failure messaging for missing ember-cli versions

### ISSUE THREAD

**Issue by timiyay** [ember-cli/ember-cli-update#818]
If you are submitting a bug report, please run your command with the debug flag:

* Unix (global): `DEBUG=ember-cli-update,boilerplate-update,git-diff-apply ember-cli-update ...`
* Windows (global): `set DEBUG=ember-cli-update,boilerplate-update,git-diff-apply && ember-cli-update ...`
* Unix (command): `DEBUG=ember-cli-update,boilerplate-update,git-diff-apply ember update ...`
* Windows (command): `set DEBUG=ember-cli-update,boilerplate-update,git-diff-apply && ember update ...`

and post the console output in the block below:

```
[console output goes here...]
```

**Comment by kellyselden** [comment]
Those are some good ideas. Regarding this message:

```
ember-cli@3.12.1 has been released, but has no corresponding release in ember-new-output. Please file an issue at https://github.com/ember-cli/ember-cli/issues.
```

We will probably want to put some sort of hour timer on it. The ember-cli release process can take an hour or so if there are issues, and some people are ready to update as soon as it reaches npm, but the output repo may not be ready yet. Giving them a message to open an issue, before it is an actual issue yet, would not be necessary.

Regarding

```
This will also update to:
- ember-source@~3.12.0
- ember-data@~3.12.0
```

That might be overkill. The tool doesn't even know about those versions. Are you aware of `ember-cli-update --compare-versions`? That would show you what is changing, including ember versions.

**Comment by timiyay** [comment]
@kellyselden thanks for the comments.

I was not aware of `--compare-versions`, I'll have a play with it. It sounds like it'll cover that portion of our problem.

I'll get a PR going that covers the basic idea - providing feedback when targeting a non-existent release of `ember-cli`.

Then, I can look at a follow-up PR, or some different messaging, that explain the ember-new-output issue.

We could potentially cover the release delay use case by looking at timestamps, though perhaps that's overcomplicated. We could keep the `has no corresponding release` message, for example, but avoid asking to open an issue, and to mention the release delay as a factor.

**Comment by Alonski** [comment]
I got something similar to this when my current version of `ember-source` was an s3 file:
`        "ember-source": "https://s3.amazonaws.com/builds.emberjs.com/canary/shas/8438cd59062d38d0624b8c07187ecc91fe78ad91.tgz",`

Got this error:
```
λ  ember-cli-update
{ Error: Command failed: git --git-dir="C:\Users\Alon\AppData\Local\Temp\tmp-296243779daiha709\.git" rev-parse vnull
fatal: ambiguous argument 'vnull': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 128,
  signal: null,
  cmd:
   'git --git-dir="C:\\Users\\Alon\\AppData\\Local\\Temp\\tmp-296243779daiha709\\.git" rev-parse vnull',
  stdout: 'vnull\n',
  stderr:
   'fatal: ambiguous argument \'vnull\': unknown revision or path not in the working tree.\nUse \'--\' to separate paths from revisions, like this:\n\'git <command> [<revision>...] -- [<file>...]\'\n' }
```

**Comment by kellyselden** [comment]
@Alonski That's an unrelated issue #685
