### ISSUE TITLE
unable to update project in subfolder

### ISSUE THREAD

**Issue by lifeart** [ember-cli/ember-cli-update#961]
repo: https://github.com/Brain-up/brn/tree/dev/frontend

```
lifeart@thinkpad-x1 MINGW64 ~/Documents/repos/brn/frontend (dev)
$ ember-cli-update
{ err:
   Error: git add frontend/app/serializers/series.js frontend/app/serializers/task.js frontend/app/serializers/task/single-words.js frontend/app/serializers/task/words-sequences.js frontend/app/services/audio.js frontend/app/services/studying-timer.js frontend/app/services/tasks-manager.js frontend/app/styles/app.css frontend/app/templates/application.hbs frontend/app/templates/components/.gitkeep frontend/app/templates/error.hbs frontend/app/templates/group.hbs frontend/app/templates/group/series.hbs frontend/app/templates/group/series/exercise.hbs frontend/app/templates/group/series/exercise/task.hbs frontend/app/templates/groups.hbs frontend/app/templates/index.hbs frontend/app/templates/not-accessable.hbs frontend/app/transforms/array.js frontend/app/utils/array-next.js 
frontend/app/utils/array-previous-items.js frontend/app/utils/custom-timeout.js frontend/app/utils/deep-copy.js frontend/app/utils/deep-equal.js frontend/app/utils/shuffle-array.js frontend/config/deploy.js frontend/config/environment.js frontend/config/optional-features.json frontend/config/targets.js frontend/ember-cli-build.js frontend/mirage/config.js frontend/mirage/factories/group.js frontend/mirage/models/exercise.js frontend/mirage/models/group.js frontend/mirage/models/series.js frontend/mirage/models/task.js frontend/mirage/scenarios/default.js frontend/mirage/serializers/application.js frontend/package.json "frontend/public/audio/no_noise/\320\261\320\260\320\273.mp3" "frontend/public/audio/no_noise/\320\261\321\203\320\274.mp3" "frontend/public/audio/no_noise/\320\261\321\213\320\273\321\214.mp3" "frontend/public/audio/no_noise/\320\262\320\270\321\202\321\214.mp3" "frontend/public/audio/no_noise/\320\263\320\260\320\264.mp3" "frontend/public/audio/no_noise/\320\264\321\203\320\261.mp3" "frontend/public/audio/no_noise/\320\273\320\270\320\275\321\214.mp3" "frontend/public/audio/no_noise/\320\273\320\270\321\201.mp3" "frontend/public/audio/no_noise/\320\274\320\276\320\273\321\214.mp3" "frontend/public/audio/no_noise/\320\274\320\276\321\200.mp3" "frontend/public/audio/no_noise/\320\277\320\260\321\200.mp3" "frontend/public/audio/no_noise/\320\277\321\217\321\202\321\214.mp3" "frontend/public/audio/no_noise/\321\200\320\260\320\261.mp3" "frontend/public/audio/no_noise/\321\200\320\260\320\272.mp3" "frontend/public/audio/no_noise/\321\200\320\276\320\266\321\214.mp3" "frontend/public/audio/no_noise/\321\201\320\265\321\202\321\214.mp3" "frontend/public/audio/no_noise/\321\202\320\276\320\277\321\214.mp3" "frontend/public/audio/no_noise/\321\205\320\276\320\264.mp3" "frontend/public/audio/no_noise/\321\210\320\265\321\204.mp3" "frontend/public/audio/noise_6db/\320\261\320\260\320\273.mp3" "frontend/public/audio/noise_6db/\320\261\321\203\320\274.mp3" "frontend/public/audio/noise_6db/\320\261\321\213\320\273\321\214.mp3" "frontend/public/audio/noise_6db/\320\262\320\270\321\202\321\214.mp3" "frontend/public/audio/noise_6db/\320\263\320\260\320\264.mp3" "frontend/public/audio/noise_6db/\320\264\321\203\320\261.mp3" "frontend/public/audio/noise_6db/\320\272\321\203\320\261.mp3" "frontend/public/audio/noise_6db/\320\273\320\270\320\275\321\214.mp3" "frontend/public/audio/noise_6db/\320\273\320\270\321\201.mp3" "frontend/public/audio/noise_6db/\320\274\320\276\320\273\321\214.mp3" "frontend/public/audio/noise_6db/\320\274\320\276\321\200.mp3" "frontend/public/audio/noise_6db/\320\277\320\260\321\200.mp3" "frontend/public/audio/noise_6db/\320\277\321\217\321\202\321\214.mp3" "frontend/public/audio/noise_6db/\321\200\320\260\320\261.mp3" "frontend/public/audio/noise_6db/\321\200\320\260\320\272.mp3" "frontend/public/audio/noise_6db/\321\200\320\276\320\266\321\214.mp3" "frontend/public/audio/noise_6db/\321\201\320\265\321\202\321\214.mp3" "frontend/public/audio/noise_6db/\321\202\320\276\320\277\321\214.mp3" "frontend/public/audio/noise_6db/\321\205\320\276\320\264.mp3" "frontend/public/audio/noise_6db/\321\210\320\265\321\204.mp3" "frontend/public/audio/noise_9db/\320\261\320\260\320\273.mp3" "frontend/public/audio/noise_9db/\320\261\321\203\320\274.mp3" "frontend/public/audio/noise_9db/\320\261\321\213\320\273\321\214.mp3" failed with message fatal: pathspec '"frontend/public/audio/no_noise/\320\261\320\260\320\273.mp3"' did not match any files

       at ChildProcess.<anonymous> (C:\Users\lifeart\AppData\Roaming\npm\node_modules\ember-cli-update\node_modules\git-diff-apply\src\run.js:34:16)
       at ChildProcess.emit (events.js:198:13)
       at maybeClose (internal/child_process.js:982:16)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5),
  err2:
   { Error: Command failed: git checkout dev
   Switched to branch 'dev'
   error Couldn't find a package.json file in "C:\\Users\\lifeart\\Documents\\repos\\brn\\frontend"

       at ChildProcess.exithandler (child_process.js:294:12)
       at ChildProcess.emit (events.js:198:13)
       at maybeClose (internal/child_process.js:982:16)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
     killed: false,
     code: 1,
     signal: null,
     cmd: 'git checkout dev',
     stdout:
      'D\tfrontend/app/serializers/series.js\nD\tfrontend/app/serializers/task.js\nD\tfrontend/app/serializers/task/single-words.js\nD\tfrontend/app/serializers/task/words-sequences.js\nD\tfrontend/app/services/audio.js\nD\tfrontend/app/services/studying-timer.js\nD\tfrontend/app/services/tasks-manager.js\nD\tfrontend/app/styles/app.css\nD\tfrontend/app/templates/application.hbs\nD\tfrontend/app/templates/components/.gitkeep\nD\tfrontend/app/templates/error.hbs\nD\tfrontend/app/templates/group.hbs\nD\tfrontend/app/templates/group/series.hbs\nD\tfrontend/app/templates/group/series/exercise.hbs\nD\tfrontend/app/templates/group/series/exercise/task.hbs\nD\tfrontend/app/templates/groups.hbs\nD\tfrontend/app/templates/index.hbs\nD\tfrontend/app/templates/not-accessable.hbs\nD\tfrontend/app/transforms/array.js\nD\tfrontend/app/utils/array-next.js\nD\tfrontend/app/utils/array-previous-items.js\nD\tfrontend/app/utils/custom-timeout.js\nD\tfrontend/app/utils/deep-copy.js\nD\tfrontend/app/utils/deep-equal.js\nD\tfrontend/app/utils/shuffle-array.js\nD\tfrontend/config/deploy.js\nD\tfrontend/config/environment.js\nD\tfrontend/config/optional-features.json\nD\tfrontend/config/targets.js\nD\tfrontend/ember-cli-build.js\nD\tfrontend/mirage/config.js\nD\tfrontend/mirage/factories/group.js\nD\tfrontend/mirage/models/exercise.js\nD\tfrontend/mirage/models/group.js\nD\tfrontend/mirage/models/series.js\nD\tfrontend/mirage/models/task.js\nD\tfrontend/mirage/scenarios/default.js\nD\tfrontend/mirage/serializers/application.js\nD\tfrontend/package.json\nYour branch is up to date with \'origin/dev\'.\n',
     stderr:
      'Switched to branch \'dev\'\nerror Couldn\'t find a package.json file in "C:\\\\Users\\\\lifeart\\\\Documents\\\\repos\\\\brn\\\\frontend"\n' } }      

```

**Comment by kellyselden** [comment]
what version of ember-cli-update do you have?

**Comment by lifeart** [comment]
v0.52.1

**Comment by kellyselden** [comment]
hmm. I didn't get any errors when trying your repo. But your app is already on the latest ember-cli version, so nothing happened.

**Comment by lifeart** [comment]
hm, it's happening with me on windows mashine

**Comment by kellyselden** [comment]
can you try it in cmd.exe instead of mingw to see if there's a difference?

**Comment by lifeart** [comment]
just checked, cannot reproduce issue, looks like it `git-bash` problem
